/**
 * inventory-engine.ts
 *
 * Sole owner of all inventory mutations. Every change to inventoryCollection
 * or inventoryMovementCollection flows through this engine — no other module
 * may write to those collections directly.
 *
 * Follows the same architectural contract as EntitlementEngine, FIFOEngine,
 * NotificationEngine: a plain exported object with named methods.
 *
 * CRITICAL CONSTRAINT (ADR-001 / Phase 3 Risk R1):
 *   All methods are synchronous. They are designed to be called from inside a
 *   dbTransaction callback. Introducing an async boundary here would break
 *   offline atomicity. If you find yourself wanting to await inside these
 *   methods, the caller — not the engine — is where async belongs.
 *
 * TENANT CONTEXT:
 *   Methods receive { userId, branchId, businessId } explicitly. The engine
 *   never reads authStore directly, making it testable and callable from any
 *   context (UI, server function, automated trigger).
 */

import type {
  inventoryCollection as InventoryCollectionType,
  inventoryMovementCollection as MovementCollectionType,
  operationalTaskCollection as TaskCollectionType,
} from '@platform/db/collections'
import { MovementType, TaskStatus, TaskType } from 'prisma/generated/prisma/enums'
import { type InventoryMode, InventoryPolicy } from '@/lib/inventory/inventory-policy'
import type { feTask } from '@/lib/queries/fetch-tasks'

// ---------------------------------------------------------------------------
// Shared tenant-context type — passed explicitly by every caller
// ---------------------------------------------------------------------------

interface TenantContext {
  /** The ID of the user performing the operation. Must be a valid, non-empty user ID. */
  userId: string
  branchId: string
  businessId: string
  /**
   * Whether SHELF_REFILL tasks generated by a LowStockDetected condition are
   * auto-approved at creation time. Sourced from configuration AUTO_APPROVE_LOW_STOCK_REFILL
   * at the call site (notification-engine.ts). Defaults to true when the config
   * is not explicitly set.
   */
  autoApproveLowStockRefill?: boolean
}

// ---------------------------------------------------------------------------
// PurchaseReceipt params — mirrors the shape produced by create-purchase.ts
// ---------------------------------------------------------------------------

export interface PurchaseReceiptItem {
  variantId: string
  quantity: number
  unitId: string
  unitCost: number
}

export interface ApplyPurchaseReceiptParams {
  purchaseId: string
  structuredId: string
  items: PurchaseReceiptItem[]
  inventoryCollection: typeof InventoryCollectionType
  movementCollection: typeof MovementCollectionType
  ctx: TenantContext
}

// ---------------------------------------------------------------------------
// PurchaseVoid params — mirrors the shape produced by void-purchase.ts
// ---------------------------------------------------------------------------

export interface ApplyPurchaseVoidParams {
  purchaseId: string
  purchaseIdDisplay: string
  items: Array<{ variantId: string; quantity: number; unitId: string }>
  movementsToReverse: Array<{
    id: string
    variantId: string
    inventoryId: string
    quantity: number
    unitId: string
    locationId: string | null
  }>
  inventoryCollection: typeof InventoryCollectionType
  movementCollection: typeof MovementCollectionType
  ctx: TenantContext
  inventoryMode: InventoryMode
}

// ---------------------------------------------------------------------------
// Adjustment params — mirrors the shape produced by restock-ingredient.ts
// ---------------------------------------------------------------------------

export interface ApplyAdjustmentParams {
  variantId: string
  batchNumber: string
  quantity: number
  locationId: string
  costPrice: number
  expiryDate: Date | null
  unitId: string
  purchaseId: string
  structuredId: string
  reason: string | null
  inventoryCollection: typeof InventoryCollectionType
  movementCollection: typeof MovementCollectionType
  ctx: TenantContext
}

// ---------------------------------------------------------------------------
// TaskFulfillment params — mirrors inventory side-effects in tasks/$taskId/index.tsx
// ---------------------------------------------------------------------------

export interface ApplyTaskFulfillmentParams {
  task: feTask
  inventoryCollection: typeof InventoryCollectionType
  movementCollection: typeof MovementCollectionType
  ctx: TenantContext
  inventoryMode: InventoryMode
}

// ---------------------------------------------------------------------------
// LowStockDetected params — for the auto-task-creation extracted from NotificationEngine
// ---------------------------------------------------------------------------

export interface HandleLowStockDetectedParams {
  variantId: string
  currentTotal: number
  threshold: number
  productLink: string
  operationalTaskCollection: typeof TaskCollectionType
  ctx: TenantContext
}

// ---------------------------------------------------------------------------
// InventoryEngine
// ---------------------------------------------------------------------------

/**
 * AUTO_APPROVE_LOW_STOCK_REFILL
 *
 * Policy exception (P-TASK-04 / Architecture Compliance Audit Deviation 3).
 *
 * Auto-generated SHELF_REFILL tasks produced by a LowStockDetected condition are
 * auto-approved at creation time by default. This is an explicit, named policy
 * exception — not a silent bypass of the approval workflow.
 *
 * Rationale: a low-stock condition represents a confirmed physical reality detected by
 * the system. The reorder decision has already been authorized implicitly by the
 * manager who set the reorder threshold. Requiring a separate explicit approval step
 * before the clerk can begin restocking introduces latency without proportionate control
 * benefit. This exception is limited to SHELF_REFILL tasks only.
 *
 * Configurable per business via configuration AUTO_APPROVE_LOW_STOCK_REFILL (boolean,
 * default: true). Pass the value through TenantContext.autoApproveLowStockRefill at
 * the call site. When false, the task enters TaskStatus.PENDING and requires a
 * supervisor to approve it before the clerk can act.
 *
 * Trigger for revisiting: if SHELF_REFILL auto-approval causes audit failures or
 * unauthorized inventory movements become a concern, set
 * configuration AUTO_APPROVE_LOW_STOCK_REFILL = false for the affected business.
 */

export const InventoryEngine = {
  /**
   * Apply inventory side-effects when a purchase is created (goods received).
   *
   * Creates or updates the inventory batch keyed by PO number, and inserts an
   * IN movement record for each line item.
   *
   * Called from create-purchase.ts inside dbTransaction.
   */
  applyPurchaseReceipt({ purchaseId, structuredId, items, inventoryCollection, movementCollection, ctx }: ApplyPurchaseReceiptParams): void {
    const now = new Date()

    for (const item of items) {
      const batchNumber = `PO-${structuredId}`
      const existingBatch = [...inventoryCollection.values()].find(i => i.variantId === item.variantId && i.batchNumber === batchNumber)

      let inventoryId: string

      if (existingBatch) {
        inventoryId = existingBatch.id
        inventoryCollection.update(inventoryId, draft => {
          draft.quantity += item.quantity
          draft.costPrice = item.unitCost
          draft.lastRestocked = now
        })
      } else {
        inventoryId = crypto.randomUUID()
        inventoryCollection.insert({
          id: inventoryId,
          variantId: item.variantId,
          quantity: item.quantity,
          unitId: item.unitId,
          batchNumber,
          costPrice: item.unitCost,
          locationId: ctx.branchId,
          expiryDate: null,
          lastRestocked: now,
          businessId: ctx.businessId,
          branchId: ctx.branchId,
          updatedAt: now,
          createdAt: now,
        })
      }

      movementCollection.insert({
        id: crypto.randomUUID(),
        variantId: item.variantId,
        inventoryId,
        userId: ctx.userId,
        quantity: item.quantity,
        unitId: item.unitId,
        type: MovementType.IN,
        reason: `Purchase Order: ${structuredId}`,
        transactionId: null,
        targetBranchId: null,
        purchaseId,
        locationId: ctx.branchId,
        businessId: ctx.businessId,
        branchId: ctx.branchId,
        updatedAt: now,
        createdAt: now,
        operationalTaskId: null,
      })
    }
  },

  /**
   * Reverse inventory side-effects when a purchase is voided.
   *
   * Prefers reversing via the original IN movements. Falls back to line-item
   * batch lookup when no movements were recorded.
   *
   * Called from void-purchase.ts inside dbTransaction.
   *
   * INVENTORY MODE ENFORCEMENT:
   *   - 'none': always allows void (no validation)
   *   - 'relaxed': allows void even if it would result in negative inventory
   *   - 'strict': throws InsufficientStockError if void would cause negative inventory
   */
  applyPurchaseVoid({
    purchaseId,
    purchaseIdDisplay,
    items,
    movementsToReverse,
    inventoryCollection,
    movementCollection,
    ctx,
    inventoryMode,
  }: ApplyPurchaseVoidParams): void {
    const now = new Date()

    if (movementsToReverse.length > 0) {
      for (const movement of movementsToReverse) {
        if (inventoryCollection.has(movement.inventoryId)) {
          const batch = inventoryCollection.get(movement.inventoryId)
          if (batch) {
            // Validate BEFORE mutation in strict mode
            InventoryPolicy.validateDeduction({
              mode: inventoryMode,
              variantId: movement.variantId,
              requested: movement.quantity,
              available: batch.quantity,
              batchId: batch.id,
              operation: 'purchase void',
            })
          }

          inventoryCollection.update(movement.inventoryId, draft => {
            // Remove Math.max(0) clamping — allow negative in relaxed mode
            draft.quantity -= movement.quantity
          })
        }

        movementCollection.insert({
          id: crypto.randomUUID(),
          variantId: movement.variantId,
          inventoryId: movement.inventoryId,
          userId: ctx.userId,
          quantity: movement.quantity,
          unitId: movement.unitId,
          type: MovementType.OUT,
          reason: `Void: ${purchaseIdDisplay}`,
          transactionId: null,
          targetBranchId: null,
          purchaseId,
          locationId: movement.locationId,
          businessId: ctx.businessId,
          branchId: ctx.branchId,
          updatedAt: now,
          createdAt: now,
          operationalTaskId: null,
        })
      }
      return
    }

    // Fallback: no movement records found — use line items with batch lookup
    for (const item of items) {
      const batch = [...inventoryCollection.values()].find(i => i.variantId === item.variantId && i.batchNumber === `PO-${purchaseIdDisplay}`)
      if (!batch) continue

      // Validate BEFORE mutation in strict mode
      InventoryPolicy.validateDeduction({
        mode: inventoryMode,
        variantId: item.variantId,
        requested: item.quantity,
        available: batch.quantity,
        batchId: batch.id,
        operation: 'purchase void',
      })

      inventoryCollection.update(batch.id, draft => {
        // Remove Math.max(0) clamping — allow negative in relaxed mode
        draft.quantity -= item.quantity
      })

      movementCollection.insert({
        id: crypto.randomUUID(),
        variantId: item.variantId,
        inventoryId: batch.id,
        userId: ctx.userId,
        quantity: item.quantity,
        unitId: item.unitId,
        type: MovementType.OUT,
        reason: `Void: ${purchaseIdDisplay}`,
        transactionId: null,
        targetBranchId: null,
        purchaseId,
        locationId: ctx.branchId,
        businessId: ctx.businessId,
        branchId: ctx.branchId,
        updatedAt: now,
        createdAt: now,
        operationalTaskId: null,
      })
    }
  },

  /**
   * Apply a manual inventory adjustment with a stated reason.
   *
   * Creates or updates the inventory batch keyed by batchNumber, and inserts
   * an IN movement record as the audit trail.
   *
   * Called from restock-ingredient.ts inside dbTransaction.
   */
  applyAdjustment({
    variantId,
    batchNumber,
    quantity,
    locationId,
    costPrice,
    expiryDate,
    unitId,
    purchaseId,
    structuredId,
    reason,
    inventoryCollection,
    movementCollection,
    ctx,
  }: ApplyAdjustmentParams): string {
    const now = new Date()

    const existingBatch = [...inventoryCollection.values()].find(i => i.variantId === variantId && i.batchNumber === batchNumber)

    let inventoryId: string

    if (existingBatch) {
      inventoryId = existingBatch.id
      inventoryCollection.update(inventoryId, draft => {
        draft.quantity += quantity
        draft.costPrice = costPrice
        draft.lastRestocked = now
      })
    } else {
      inventoryId = crypto.randomUUID()
      inventoryCollection.insert({
        id: inventoryId,
        variantId,
        quantity,
        unitId,
        batchNumber,
        costPrice,
        locationId,
        expiryDate,
        lastRestocked: now,
        businessId: ctx.businessId,
        branchId: ctx.branchId,
        updatedAt: now,
        createdAt: now,
      })
    }

    movementCollection.insert({
      id: crypto.randomUUID(),
      variantId,
      inventoryId,
      userId: ctx.userId,
      quantity,
      unitId,
      type: MovementType.IN,
      reason: `${reason || 'Restock'}: ${structuredId}`,
      transactionId: null,
      targetBranchId: null,
      purchaseId,
      locationId,
      businessId: ctx.businessId,
      branchId: ctx.branchId,
      updatedAt: now,
      createdAt: now,
      operationalTaskId: null,
    })

    return inventoryId
  },

  /**
   * Apply inventory side-effects when a task is marked as FULFILLED.
   *
   * Handles four task types:
   *   SHELF_REFILL      — deduct source location batch, credit target location batch
   *   BRANCH_TRANSFER   — deduct sending branch (OUT), credit receiving branch (IN)
   *   STOCK_COUNT       — set batch quantity to physically counted value
   *   WASTE_DISPOSAL    — deduct wasted quantity from batch
   *
   * B6 fix applied: WASTE_DISPOSAL uses 'WASTE' movement type (not 'OUT').
   *                 BRANCH_TRANSFER uses 'EXTERNAL_TRANSFER' (not 'ADJUST').
   *                 SHELF_REFILL uses 'INTERNAL_TRANSFER' (not 'ADJUST').
   * B7 fix applied: BRANCH_TRANSFER now inserts a second IN movement scoped to the
   *                 receiving branch's branchId, providing the cross-branch audit trail entry.
   *
   * INVENTORY MODE ENFORCEMENT:
   *   - 'none': always allows task fulfillment (no validation)
   *   - 'relaxed': allows task fulfillment even if it would result in negative inventory
   *   - 'strict': throws InsufficientStockError if task would cause negative inventory
   *
   * Called from tasks/$taskId/index.tsx inside dbTransaction.
   */
  applyTaskFulfillment({ task, inventoryCollection, movementCollection, ctx, inventoryMode }: ApplyTaskFulfillmentParams): void {
    const meta = task.metadata
    const variantId = meta?.variantId
    // C4: Use the most specific quantity available.
    // verifiedQty — what the clerk actually moved (recorded at IN_PROGRESS stage)
    // approvedQty — what the manager authorized (recorded at PENDING stage)
    // suggestedQty — the original creator estimate (fallback)
    const qty = meta?.verifiedQty ?? meta?.approvedQty ?? meta?.suggestedQty ?? 0

    if (!variantId || qty <= 0) return

    const timestamp = new Date()
    const movementBase = {
      variantId,
      userId: ctx.userId,
      transactionId: null,
      purchaseId: null,
      operationalTaskId: task.id,
      businessId: ctx.businessId,
      branchId: ctx.branchId,
      updatedAt: timestamp,
      createdAt: timestamp,
    }

    if (task.type === TaskType.SHELF_REFILL) {
      const sourceId = meta?.sourceLocationId
      const targetId = meta?.targetLocationId

      const sourceBatch = [...inventoryCollection.values()].find(i => i.variantId === variantId && i.locationId === sourceId && i.quantity > 0)

      if (sourceBatch) {
        // Validate BEFORE mutation in strict mode
        InventoryPolicy.validateDeduction({
          mode: inventoryMode,
          variantId,
          requested: qty,
          available: sourceBatch.quantity,
          batchId: sourceBatch.id,
          operation: 'shelf refill',
        })

        inventoryCollection.update(sourceBatch.id, draft => {
          // Remove Math.min — allow negative in relaxed mode
          draft.quantity -= qty
        })
      }

      const targetBatch = [...inventoryCollection.values()].find(i => i.variantId === variantId && i.locationId === targetId)

      if (targetBatch) {
        inventoryCollection.update(targetBatch.id, draft => {
          draft.quantity += qty
        })
      } else {
        inventoryCollection.insert({
          id: crypto.randomUUID(),
          variantId,
          quantity: qty,
          unitId: sourceBatch?.unitId ?? '',
          batchNumber: 'SHELF-REFILL',
          costPrice: sourceBatch?.costPrice ?? 0,
          locationId: targetId ?? null,
          expiryDate: null,
          lastRestocked: timestamp,
          businessId: ctx.businessId,
          branchId: ctx.branchId,
          updatedAt: timestamp,
          createdAt: timestamp,
        })
      }

      movementCollection.insert({
        ...movementBase,
        id: crypto.randomUUID(),
        // B6 fix: SHELF_REFILL uses INTERNAL_TRANSFER, not ADJUST
        type: MovementType.INTERNAL_TRANSFER,
        quantity: qty,
        unitId: sourceBatch?.unitId ?? '',
        reason: `Shelf Refill: Task #${task.id.slice(0, 8)}`,
        locationId: targetId ?? null,
        targetBranchId: null,
        inventoryId: targetBatch?.id ?? crypto.randomUUID(),
      })
      return
    }

    if (task.type === TaskType.BRANCH_TRANSFER) {
      const targetBranchId = meta?.targetBranchId ?? null
      const sourceBatch = [...inventoryCollection.values()].find(i => i.variantId === variantId && i.quantity > 0)

      if (sourceBatch) {
        // Validate BEFORE mutation in strict mode
        InventoryPolicy.validateBatchTransfer({
          mode: inventoryMode,
          variantId,
          requested: qty,
          available: sourceBatch.quantity,
          batchId: sourceBatch.id,
        })

        inventoryCollection.update(sourceBatch.id, draft => {
          // Remove Math.min — allow negative in relaxed mode
          draft.quantity -= qty
        })
      }

      // OUT movement on the source branch
      movementCollection.insert({
        ...movementBase,
        id: crypto.randomUUID(),
        // B6 fix: BRANCH_TRANSFER uses EXTERNAL_TRANSFER, not ADJUST
        type: MovementType.EXTERNAL_TRANSFER,
        quantity: qty,
        unitId: sourceBatch?.unitId ?? '',
        reason: `Branch Transfer (out): Task #${task.id.slice(0, 8)}`,
        locationId: sourceBatch?.locationId ?? null,
        targetBranchId,
        inventoryId: sourceBatch?.id ?? crypto.randomUUID(),
      })

      // B7: IN movement on the receiving branch — credits destination inventory ledger.
      // branchId is set to targetBranchId so the movement is scoped to the receiving branch.
      // The inventory record itself is not created here — that belongs to the receiving branch's
      // InventoryEngine.applyAdjustment call when they accept the transfer. The movement record
      // is the cross-branch audit trail entry.
      if (targetBranchId) {
        movementCollection.insert({
          ...movementBase,
          id: crypto.randomUUID(),
          type: MovementType.IN,
          quantity: qty,
          unitId: sourceBatch?.unitId ?? '',
          reason: `Branch Transfer (in): Task #${task.id.slice(0, 8)}`,
          locationId: null,
          targetBranchId: null,
          // scope this movement to the receiving branch
          branchId: targetBranchId,
          inventoryId: sourceBatch?.id ?? crypto.randomUUID(),
        })
      }

      return
    }

    if (task.type === TaskType.STOCK_COUNT) {
      const existingBatch = [...inventoryCollection.values()].find(i => i.variantId === variantId && i.locationId === (meta?.locationId ?? null))

      if (existingBatch) {
        const diff = qty - existingBatch.quantity
        inventoryCollection.update(existingBatch.id, draft => {
          draft.quantity = qty
        })
        movementCollection.insert({
          ...movementBase,
          id: crypto.randomUUID(),
          type: MovementType.ADJUST,
          quantity: Math.abs(diff),
          unitId: existingBatch.unitId,
          reason: `Stock Count Reconciliation: Task #${task.id.slice(0, 8)} (${diff >= 0 ? '+' : ''}${diff})`,
          locationId: meta?.locationId ?? null,
          targetBranchId: null,
          inventoryId: existingBatch.id,
        })
      }
      return
    }

    if (task.type === TaskType.WASTE_DISPOSAL) {
      const wasteLocationId = meta?.locationId ?? null
      const batch = [...inventoryCollection.values()].find(i => i.variantId === variantId && i.locationId === wasteLocationId && i.quantity > 0)

      if (batch) {
        // Validate BEFORE mutation in strict mode
        InventoryPolicy.validateWasteDisposal({
          mode: inventoryMode,
          variantId,
          requested: qty,
          available: batch.quantity,
          batchId: batch.id,
        })

        inventoryCollection.update(batch.id, draft => {
          // Remove Math.min — allow negative in relaxed mode
          draft.quantity -= qty
        })
        movementCollection.insert({
          ...movementBase,
          id: crypto.randomUUID(),
          // B6 fix: WASTE_DISPOSAL uses WASTE, not OUT
          type: MovementType.WASTE,
          quantity: qty,
          unitId: batch.unitId,
          reason: `Waste Disposal: Task #${task.id.slice(0, 8)}`,
          locationId: wasteLocationId,
          targetBranchId: null,
          inventoryId: batch.id,
        })
      }
    }
  },

  /**
   * Create the auto-generated SHELF_REFILL task when a LowStockDetected
   * condition is confirmed. This is the task-creation logic extracted from
   * NotificationEngine.checkLowStock (A6 — cross-domain violation fix).
   *
   * The Notification domain retains only the send() call after this method
   * handles the task record insertion.
   *
   * Called from NotificationEngine.checkLowStock inside dbTransaction.
   *
   * Auto-approval behaviour is governed by configuration AUTO_APPROVE_LOW_STOCK_REFILL
   * passed through ctx.autoApproveLowStockRefill (see module-level policy comment above).
   */
  handleLowStockDetected({ variantId, currentTotal, threshold, productLink, operationalTaskCollection, ctx }: HandleLowStockDetectedParams): void {
    const suggestedQty = threshold - currentTotal > 0 ? threshold - currentTotal : 10
    const now = new Date()
    // Read from configuration — defaults to true when not explicitly configured.
    const autoApprove = ctx.autoApproveLowStockRefill ?? true

    operationalTaskCollection.insert({
      id: crypto.randomUUID(),
      type: TaskType.SHELF_REFILL,
      // AUTO_APPROVE_LOW_STOCK_REFILL: when true, the task is inserted directly
      // into IN_PROGRESS (approved + started) so the clerk can act immediately.
      // When false, the task enters PENDING and requires a supervisor to approve it.
      status: autoApprove ? TaskStatus.IN_PROGRESS : TaskStatus.PENDING,
      notes: `Auto-generated task: Low stock threshold breached for variant ${variantId}`,
      dueDate: now,
      creatorId: ctx.userId,
      approverId: autoApprove ? ctx.userId : null,
      clerkId: ctx.userId,
      metadata: {
        variantId,
        currentTotal,
        link: productLink,
        suggestedQty,
        approvedQty: suggestedQty,
        verifiedQty: null,
      },
      approvedAt: autoApprove ? now : null,
      inProgressAt: autoApprove ? now : null,
      fulfilledAt: null,
      businessId: ctx.businessId,
      branchId: ctx.branchId,
      createdAt: now,
      updatedAt: now,
      reviewedAt: null,
      reviewerId: null,
      canceledAt: null,
      cancelerId: null,
    })
  },
}
