/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as privateRouteRouteImport } from './routes/(private)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as privatedashboardRouteRouteImport } from './routes/(private)/(dashboard)/route'
import { Route as privatePosIndexRouteImport } from './routes/(private)/pos/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as privatedashboardsupervisorRouteRouteImport } from './routes/(private)/(dashboard)/(supervisor)/route'
import { Route as privatedashboardadminRouteRouteImport } from './routes/(private)/(dashboard)/(admin)/route'
import { Route as privatedashboardsupervisorSalesReportsRouteImport } from './routes/(private)/(dashboard)/(supervisor)/sales-reports'
import { Route as privatedashboardsupervisorInventoryReportsRouteImport } from './routes/(private)/(dashboard)/(supervisor)/inventory-reports'
import { Route as privatedashboardadminIngredientsRouteImport } from './routes/(private)/(dashboard)/(admin)/ingredients'
import { Route as privatedashboardadminProductsIndexRouteImport } from './routes/(private)/(dashboard)/(admin)/products/index'
import { Route as privatedashboardadminEmployeesIndexRouteImport } from './routes/(private)/(dashboard)/(admin)/employees/index'
import { Route as privatedashboardadminProductsCreateRouteImport } from './routes/(private)/(dashboard)/(admin)/products/create'
import { Route as privatedashboardadminEmployeesCreateRouteImport } from './routes/(private)/(dashboard)/(admin)/employees/create'
import { Route as privatedashboardadminEmployeesEmployeeIdRouteImport } from './routes/(private)/(dashboard)/(admin)/employees/$employeeId'

const privateRouteRoute = privateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const privatedashboardRouteRoute = privatedashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => privateRouteRoute,
} as any)
const privatePosIndexRoute = privatePosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => privateRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const privatedashboardsupervisorRouteRoute =
  privatedashboardsupervisorRouteRouteImport.update({
    id: '/(supervisor)',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardadminRouteRoute =
  privatedashboardadminRouteRouteImport.update({
    id: '/(admin)',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardsupervisorSalesReportsRoute =
  privatedashboardsupervisorSalesReportsRouteImport.update({
    id: '/sales-reports',
    path: '/sales-reports',
    getParentRoute: () => privatedashboardsupervisorRouteRoute,
  } as any)
const privatedashboardsupervisorInventoryReportsRoute =
  privatedashboardsupervisorInventoryReportsRouteImport.update({
    id: '/inventory-reports',
    path: '/inventory-reports',
    getParentRoute: () => privatedashboardsupervisorRouteRoute,
  } as any)
const privatedashboardadminIngredientsRoute =
  privatedashboardadminIngredientsRouteImport.update({
    id: '/ingredients',
    path: '/ingredients',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardadminProductsIndexRoute =
  privatedashboardadminProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardadminEmployeesIndexRoute =
  privatedashboardadminEmployeesIndexRouteImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardadminProductsCreateRoute =
  privatedashboardadminProductsCreateRouteImport.update({
    id: '/products/create',
    path: '/products/create',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardadminEmployeesCreateRoute =
  privatedashboardadminEmployeesCreateRouteImport.update({
    id: '/employees/create',
    path: '/employees/create',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardadminEmployeesEmployeeIdRoute =
  privatedashboardadminEmployeesEmployeeIdRouteImport.update({
    id: '/employees/$employeeId',
    path: '/employees/$employeeId',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof publicLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/pos/': typeof privatePosIndexRoute
  '/ingredients': typeof privatedashboardadminIngredientsRoute
  '/inventory-reports': typeof privatedashboardsupervisorInventoryReportsRoute
  '/sales-reports': typeof privatedashboardsupervisorSalesReportsRoute
  '/employees/$employeeId': typeof privatedashboardadminEmployeesEmployeeIdRoute
  '/employees/create': typeof privatedashboardadminEmployeesCreateRoute
  '/products/create': typeof privatedashboardadminProductsCreateRoute
  '/employees/': typeof privatedashboardadminEmployeesIndexRoute
  '/products/': typeof privatedashboardadminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof publicLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/pos': typeof privatePosIndexRoute
  '/ingredients': typeof privatedashboardadminIngredientsRoute
  '/inventory-reports': typeof privatedashboardsupervisorInventoryReportsRoute
  '/sales-reports': typeof privatedashboardsupervisorSalesReportsRoute
  '/employees/$employeeId': typeof privatedashboardadminEmployeesEmployeeIdRoute
  '/employees/create': typeof privatedashboardadminEmployeesCreateRoute
  '/products/create': typeof privatedashboardadminProductsCreateRoute
  '/employees': typeof privatedashboardadminEmployeesIndexRoute
  '/products': typeof privatedashboardadminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(private)': typeof privateRouteRouteWithChildren
  '/(private)/(dashboard)': typeof privatedashboardRouteRouteWithChildren
  '/(public)/login': typeof publicLoginRoute
  '/(private)/(dashboard)/(admin)': typeof privatedashboardadminRouteRouteWithChildren
  '/(private)/(dashboard)/(supervisor)': typeof privatedashboardsupervisorRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(private)/pos/': typeof privatePosIndexRoute
  '/(private)/(dashboard)/(admin)/ingredients': typeof privatedashboardadminIngredientsRoute
  '/(private)/(dashboard)/(supervisor)/inventory-reports': typeof privatedashboardsupervisorInventoryReportsRoute
  '/(private)/(dashboard)/(supervisor)/sales-reports': typeof privatedashboardsupervisorSalesReportsRoute
  '/(private)/(dashboard)/(admin)/employees/$employeeId': typeof privatedashboardadminEmployeesEmployeeIdRoute
  '/(private)/(dashboard)/(admin)/employees/create': typeof privatedashboardadminEmployeesCreateRoute
  '/(private)/(dashboard)/(admin)/products/create': typeof privatedashboardadminProductsCreateRoute
  '/(private)/(dashboard)/(admin)/employees/': typeof privatedashboardadminEmployeesIndexRoute
  '/(private)/(dashboard)/(admin)/products/': typeof privatedashboardadminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/pos/'
    | '/ingredients'
    | '/inventory-reports'
    | '/sales-reports'
    | '/employees/$employeeId'
    | '/employees/create'
    | '/products/create'
    | '/employees/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/pos'
    | '/ingredients'
    | '/inventory-reports'
    | '/sales-reports'
    | '/employees/$employeeId'
    | '/employees/create'
    | '/products/create'
    | '/employees'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/(private)'
    | '/(private)/(dashboard)'
    | '/(public)/login'
    | '/(private)/(dashboard)/(admin)'
    | '/(private)/(dashboard)/(supervisor)'
    | '/api/auth/$'
    | '/(private)/pos/'
    | '/(private)/(dashboard)/(admin)/ingredients'
    | '/(private)/(dashboard)/(supervisor)/inventory-reports'
    | '/(private)/(dashboard)/(supervisor)/sales-reports'
    | '/(private)/(dashboard)/(admin)/employees/$employeeId'
    | '/(private)/(dashboard)/(admin)/employees/create'
    | '/(private)/(dashboard)/(admin)/products/create'
    | '/(private)/(dashboard)/(admin)/employees/'
    | '/(private)/(dashboard)/(admin)/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  privateRouteRoute: typeof privateRouteRouteWithChildren
  publicLoginRoute: typeof publicLoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/(dashboard)': {
      id: '/(private)/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privatedashboardRouteRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/pos/': {
      id: '/(private)/pos/'
      path: '/pos'
      fullPath: '/pos/'
      preLoaderRoute: typeof privatePosIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/(dashboard)/(supervisor)': {
      id: '/(private)/(dashboard)/(supervisor)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privatedashboardsupervisorRouteRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/(admin)': {
      id: '/(private)/(dashboard)/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privatedashboardadminRouteRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/(supervisor)/sales-reports': {
      id: '/(private)/(dashboard)/(supervisor)/sales-reports'
      path: '/sales-reports'
      fullPath: '/sales-reports'
      preLoaderRoute: typeof privatedashboardsupervisorSalesReportsRouteImport
      parentRoute: typeof privatedashboardsupervisorRouteRoute
    }
    '/(private)/(dashboard)/(supervisor)/inventory-reports': {
      id: '/(private)/(dashboard)/(supervisor)/inventory-reports'
      path: '/inventory-reports'
      fullPath: '/inventory-reports'
      preLoaderRoute: typeof privatedashboardsupervisorInventoryReportsRouteImport
      parentRoute: typeof privatedashboardsupervisorRouteRoute
    }
    '/(private)/(dashboard)/(admin)/ingredients': {
      id: '/(private)/(dashboard)/(admin)/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof privatedashboardadminIngredientsRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/(admin)/products/': {
      id: '/(private)/(dashboard)/(admin)/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof privatedashboardadminProductsIndexRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/(admin)/employees/': {
      id: '/(private)/(dashboard)/(admin)/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof privatedashboardadminEmployeesIndexRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/(admin)/products/create': {
      id: '/(private)/(dashboard)/(admin)/products/create'
      path: '/products/create'
      fullPath: '/products/create'
      preLoaderRoute: typeof privatedashboardadminProductsCreateRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/(admin)/employees/create': {
      id: '/(private)/(dashboard)/(admin)/employees/create'
      path: '/employees/create'
      fullPath: '/employees/create'
      preLoaderRoute: typeof privatedashboardadminEmployeesCreateRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/(admin)/employees/$employeeId': {
      id: '/(private)/(dashboard)/(admin)/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof privatedashboardadminEmployeesEmployeeIdRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
  }
}

interface privatedashboardadminRouteRouteChildren {
  privatedashboardadminIngredientsRoute: typeof privatedashboardadminIngredientsRoute
  privatedashboardadminEmployeesEmployeeIdRoute: typeof privatedashboardadminEmployeesEmployeeIdRoute
  privatedashboardadminEmployeesCreateRoute: typeof privatedashboardadminEmployeesCreateRoute
  privatedashboardadminProductsCreateRoute: typeof privatedashboardadminProductsCreateRoute
  privatedashboardadminEmployeesIndexRoute: typeof privatedashboardadminEmployeesIndexRoute
  privatedashboardadminProductsIndexRoute: typeof privatedashboardadminProductsIndexRoute
}

const privatedashboardadminRouteRouteChildren: privatedashboardadminRouteRouteChildren =
  {
    privatedashboardadminIngredientsRoute:
      privatedashboardadminIngredientsRoute,
    privatedashboardadminEmployeesEmployeeIdRoute:
      privatedashboardadminEmployeesEmployeeIdRoute,
    privatedashboardadminEmployeesCreateRoute:
      privatedashboardadminEmployeesCreateRoute,
    privatedashboardadminProductsCreateRoute:
      privatedashboardadminProductsCreateRoute,
    privatedashboardadminEmployeesIndexRoute:
      privatedashboardadminEmployeesIndexRoute,
    privatedashboardadminProductsIndexRoute:
      privatedashboardadminProductsIndexRoute,
  }

const privatedashboardadminRouteRouteWithChildren =
  privatedashboardadminRouteRoute._addFileChildren(
    privatedashboardadminRouteRouteChildren,
  )

interface privatedashboardsupervisorRouteRouteChildren {
  privatedashboardsupervisorInventoryReportsRoute: typeof privatedashboardsupervisorInventoryReportsRoute
  privatedashboardsupervisorSalesReportsRoute: typeof privatedashboardsupervisorSalesReportsRoute
}

const privatedashboardsupervisorRouteRouteChildren: privatedashboardsupervisorRouteRouteChildren =
  {
    privatedashboardsupervisorInventoryReportsRoute:
      privatedashboardsupervisorInventoryReportsRoute,
    privatedashboardsupervisorSalesReportsRoute:
      privatedashboardsupervisorSalesReportsRoute,
  }

const privatedashboardsupervisorRouteRouteWithChildren =
  privatedashboardsupervisorRouteRoute._addFileChildren(
    privatedashboardsupervisorRouteRouteChildren,
  )

interface privatedashboardRouteRouteChildren {
  privatedashboardadminRouteRoute: typeof privatedashboardadminRouteRouteWithChildren
  privatedashboardsupervisorRouteRoute: typeof privatedashboardsupervisorRouteRouteWithChildren
}

const privatedashboardRouteRouteChildren: privatedashboardRouteRouteChildren = {
  privatedashboardadminRouteRoute: privatedashboardadminRouteRouteWithChildren,
  privatedashboardsupervisorRouteRoute:
    privatedashboardsupervisorRouteRouteWithChildren,
}

const privatedashboardRouteRouteWithChildren =
  privatedashboardRouteRoute._addFileChildren(
    privatedashboardRouteRouteChildren,
  )

interface privateRouteRouteChildren {
  privatedashboardRouteRoute: typeof privatedashboardRouteRouteWithChildren
  privatePosIndexRoute: typeof privatePosIndexRoute
}

const privateRouteRouteChildren: privateRouteRouteChildren = {
  privatedashboardRouteRoute: privatedashboardRouteRouteWithChildren,
  privatePosIndexRoute: privatePosIndexRoute,
}

const privateRouteRouteWithChildren = privateRouteRoute._addFileChildren(
  privateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  privateRouteRoute: privateRouteRouteWithChildren,
  publicLoginRoute: publicLoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
