/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as privateRouteRouteImport } from './routes/(private)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as privatedashboardRouteRouteImport } from './routes/(private)/(dashboard)/route'
import { Route as privateTasksIndexRouteImport } from './routes/(private)/tasks/index'
import { Route as privatePosIndexRouteImport } from './routes/(private)/pos/index'
import { Route as privateOrdersIndexRouteImport } from './routes/(private)/orders/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as privatedashboardNotificationsRouteImport } from './routes/(private)/(dashboard)/notifications'
import { Route as privatedashboardadminRouteRouteImport } from './routes/(private)/(dashboard)/(admin)/route'
import { Route as privatedashboardsupervisorRouteRouteImport } from './routes/(private)/(dashboard)/(supervisor)/route'
import { Route as privatedashboardsettingsRouteRouteImport } from './routes/(private)/(dashboard)/settings/route'
import { Route as privateTasksCreateIndexRouteImport } from './routes/(private)/tasks/create/index'
import { Route as privateTasksTaskIdIndexRouteImport } from './routes/(private)/tasks/$taskId/index'
import { Route as privatedashboardSettingsIndexRouteImport } from './routes/(private)/(dashboard)/settings/index'
import { Route as privatedashboardsupervisorSalesReportsIndexRouteImport } from './routes/(private)/(dashboard)/(supervisor)/sales-reports/index'
import { Route as privatedashboardsupervisorInventoryReportsIndexRouteImport } from './routes/(private)/(dashboard)/(supervisor)/inventory-reports/index'
import { Route as privatedashboardadminProductsIndexRouteImport } from './routes/(private)/(dashboard)/(admin)/products/index'
import { Route as privatedashboardadminIngredientsIndexRouteImport } from './routes/(private)/(dashboard)/(admin)/ingredients/index'
import { Route as privatedashboardadminEmployeesIndexRouteImport } from './routes/(private)/(dashboard)/(admin)/employees/index'
import { Route as privatedashboardadminProductsCreateIndexRouteImport } from './routes/(private)/(dashboard)/(admin)/products/create/index'
import { Route as privatedashboardadminPurchasesIndexRouteImport } from './routes/(private)/(dashboard)/(admin)/purchases/index'
import { Route as privatedashboardadminPurchasesCreateIndexRouteImport } from './routes/(private)/(dashboard)/(admin)/purchases/create/index'
import { Route as privatedashboardadminProductsProductIdIndexRouteImport } from './routes/(private)/(dashboard)/(admin)/products/$productId/index'
import { Route as privatedashboardadminPurchasesPurchaseIdIndexRouteImport } from './routes/(private)/(dashboard)/(admin)/purchases/$purchaseId/index'
import { Route as privatedashboardadminIngredientsCreateIndexRouteImport } from './routes/(private)/(dashboard)/(admin)/ingredients/create/index'
import { Route as privatedashboardadminIngredientsIngredientIdIndexRouteImport } from './routes/(private)/(dashboard)/(admin)/ingredients/$ingredientId/index'
import { Route as privatedashboardadminEmployeesCreateIndexRouteImport } from './routes/(private)/(dashboard)/(admin)/employees/create/index'
import { Route as privatedashboardadminEmployeesEmployeeIdIndexRouteImport } from './routes/(private)/(dashboard)/(admin)/employees/$employeeId/index'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateRouteRoute = privateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => publicRouteRoute,
} as any)
const privatedashboardRouteRoute = privatedashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateTasksIndexRoute = privateTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => privateRouteRoute,
} as any)
const privatePosIndexRoute = privatePosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateOrdersIndexRoute = privateOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => privateRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const privatedashboardNotificationsRoute =
  privatedashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardadminRouteRoute =
  privatedashboardadminRouteRouteImport.update({
    id: '/(admin)',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardsupervisorRouteRoute =
  privatedashboardsupervisorRouteRouteImport.update({
    id: '/(supervisor)',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardsettingsRouteRoute =
  privatedashboardsettingsRouteRouteImport.update({
    id: '/settings',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privateTasksCreateIndexRoute = privateTasksCreateIndexRouteImport.update({
  id: '/tasks/create/',
  path: '/tasks/create/',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateTasksTaskIdIndexRoute = privateTasksTaskIdIndexRouteImport.update({
  id: '/tasks/$taskId/',
  path: '/tasks/$taskId/',
  getParentRoute: () => privateRouteRoute,
} as any)
const privatedashboardSettingsIndexRoute =
  privatedashboardSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => privatedashboardsettingsRouteRoute,
  } as any)
const privatedashboardsupervisorSalesReportsIndexRoute =
  privatedashboardsupervisorSalesReportsIndexRouteImport.update({
    id: '/(supervisor)/sales-reports/',
    path: '/sales-reports/',
    getParentRoute: () => privatedashboardsupervisorRouteRoute,
  } as any)
const privatedashboardsupervisorInventoryReportsIndexRoute =
  privatedashboardsupervisorInventoryReportsIndexRouteImport.update({
    id: '/(supervisor)/inventory-reports/',
    path: '/inventory-reports/',
    getParentRoute: () => privatedashboardsupervisorRouteRoute,
  } as any)
const privatedashboardadminProductsIndexRoute =
  privatedashboardadminProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardadminIngredientsIndexRoute =
  privatedashboardadminIngredientsIndexRouteImport.update({
    id: '/ingredients/',
    path: '/ingredients/',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardadminEmployeesIndexRoute =
  privatedashboardadminEmployeesIndexRouteImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardadminProductsCreateIndexRoute =
  privatedashboardadminProductsCreateIndexRouteImport.update({
    id: '/products/create/',
    path: '/products/create/',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardadminPurchasesIndexRoute =
  privatedashboardadminPurchasesIndexRouteImport.update({
    id: '/purchases/',
    path: '/purchases/',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardadminPurchasesCreateIndexRoute =
  privatedashboardadminPurchasesCreateIndexRouteImport.update({
    id: '/purchases/create/',
    path: '/purchases/create/',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardadminPurchasesPurchaseIdIndexRoute =
  privatedashboardadminPurchasesPurchaseIdIndexRouteImport.update({
    id: '/purchases/$purchaseId/',
    path: '/purchases/$purchaseId/',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardadminProductsProductIdIndexRoute =
  privatedashboardadminProductsProductIdIndexRouteImport.update({
    id: '/products/$productId/',
    path: '/products/$productId/',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardadminIngredientsCreateIndexRoute =
  privatedashboardadminIngredientsCreateIndexRouteImport.update({
    id: '/ingredients/create/',
    path: '/ingredients/create/',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardadminIngredientsIngredientIdIndexRoute =
  privatedashboardadminIngredientsIngredientIdIndexRouteImport.update({
    id: '/ingredients/$ingredientId/',
    path: '/ingredients/$ingredientId/',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardadminEmployeesCreateIndexRoute =
  privatedashboardadminEmployeesCreateIndexRouteImport.update({
    id: '/employees/create/',
    path: '/employees/create/',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardadminEmployeesEmployeeIdIndexRoute =
  privatedashboardadminEmployeesEmployeeIdIndexRouteImport.update({
    id: '/employees/$employeeId/',
    path: '/employees/$employeeId/',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/unauthorized': typeof UnauthorizedRoute
  '/login': typeof publicLoginRoute
  '/': typeof publicIndexRoute
  '/notifications': typeof privatedashboardNotificationsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/orders/': typeof privateOrdersIndexRoute
  '/pos/': typeof privatePosIndexRoute
  '/tasks/': typeof privateTasksIndexRoute
  '/settings/': typeof privatedashboardSettingsIndexRoute
  '/tasks/$taskId/': typeof privateTasksTaskIdIndexRoute
  '/tasks/create/': typeof privateTasksCreateIndexRoute
  '/employees/': typeof privatedashboardadminEmployeesIndexRoute
  '/ingredients/': typeof privatedashboardadminIngredientsIndexRoute
  '/products/': typeof privatedashboardadminProductsIndexRoute
  '/inventory-reports/': typeof privatedashboardsupervisorInventoryReportsIndexRoute
  '/sales-reports/': typeof privatedashboardsupervisorSalesReportsIndexRoute
  '/employees/$employeeId/': typeof privatedashboardadminEmployeesEmployeeIdIndexRoute
  '/employees/create/': typeof privatedashboardadminEmployeesCreateIndexRoute
  '/ingredients/$ingredientId/': typeof privatedashboardadminIngredientsIngredientIdIndexRoute
  '/ingredients/create/': typeof privatedashboardadminIngredientsCreateIndexRoute
  '/products/$productId/': typeof privatedashboardadminProductsProductIdIndexRoute
  '/purchases/': typeof privatedashboardadminPurchasesIndexRoute
  '/purchases/create/': typeof privatedashboardadminPurchasesCreateIndexRoute
  '/purchases/$purchaseId/': typeof privatedashboardadminPurchasesPurchaseIdIndexRoute
  '/products/create/': typeof privatedashboardadminProductsCreateIndexRoute
}
export interface FileRoutesByTo {
  '/unauthorized': typeof UnauthorizedRoute
  '/login': typeof publicLoginRoute
  '/': typeof publicIndexRoute
  '/notifications': typeof privatedashboardNotificationsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/orders': typeof privateOrdersIndexRoute
  '/pos': typeof privatePosIndexRoute
  '/tasks': typeof privateTasksIndexRoute
  '/settings': typeof privatedashboardSettingsIndexRoute
  '/tasks/$taskId': typeof privateTasksTaskIdIndexRoute
  '/tasks/create': typeof privateTasksCreateIndexRoute
  '/employees': typeof privatedashboardadminEmployeesIndexRoute
  '/ingredients': typeof privatedashboardadminIngredientsIndexRoute
  '/products': typeof privatedashboardadminProductsIndexRoute
  '/inventory-reports': typeof privatedashboardsupervisorInventoryReportsIndexRoute
  '/sales-reports': typeof privatedashboardsupervisorSalesReportsIndexRoute
  '/employees/$employeeId': typeof privatedashboardadminEmployeesEmployeeIdIndexRoute
  '/employees/create': typeof privatedashboardadminEmployeesCreateIndexRoute
  '/ingredients/$ingredientId': typeof privatedashboardadminIngredientsIngredientIdIndexRoute
  '/ingredients/create': typeof privatedashboardadminIngredientsCreateIndexRoute
  '/products/$productId': typeof privatedashboardadminProductsProductIdIndexRoute
  '/purchases': typeof privatedashboardadminPurchasesIndexRoute
  '/purchases/create': typeof privatedashboardadminPurchasesCreateIndexRoute
  '/purchases/$purchaseId': typeof privatedashboardadminPurchasesPurchaseIdIndexRoute
  '/products/create': typeof privatedashboardadminProductsCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(private)': typeof privateRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/(private)/(dashboard)': typeof privatedashboardRouteRouteWithChildren
  '/(public)/login': typeof publicLoginRoute
  '/(public)/': typeof publicIndexRoute
  '/(private)/(dashboard)/(admin)': typeof privatedashboardadminRouteRouteWithChildren
  '/(private)/(dashboard)/(supervisor)': typeof privatedashboardsupervisorRouteRouteWithChildren
  '/(private)/(dashboard)/settings': typeof privatedashboardsettingsRouteRouteWithChildren
  '/(private)/(dashboard)/notifications': typeof privatedashboardNotificationsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(private)/orders/': typeof privateOrdersIndexRoute
  '/(private)/pos/': typeof privatePosIndexRoute
  '/(private)/tasks/': typeof privateTasksIndexRoute
  '/(private)/(dashboard)/settings/': typeof privatedashboardSettingsIndexRoute
  '/(private)/tasks/$taskId/': typeof privateTasksTaskIdIndexRoute
  '/(private)/tasks/create/': typeof privateTasksCreateIndexRoute
  '/(private)/(dashboard)/(admin)/employees/': typeof privatedashboardadminEmployeesIndexRoute
  '/(private)/(dashboard)/(admin)/ingredients/': typeof privatedashboardadminIngredientsIndexRoute
  '/(private)/(dashboard)/(admin)/products/': typeof privatedashboardadminProductsIndexRoute
  '/(private)/(dashboard)/(supervisor)/inventory-reports/': typeof privatedashboardsupervisorInventoryReportsIndexRoute
  '/(private)/(dashboard)/(supervisor)/sales-reports/': typeof privatedashboardsupervisorSalesReportsIndexRoute
  '/(private)/(dashboard)/(admin)/employees/$employeeId/': typeof privatedashboardadminEmployeesEmployeeIdIndexRoute
  '/(private)/(dashboard)/(admin)/employees/create/': typeof privatedashboardadminEmployeesCreateIndexRoute
  '/(private)/(dashboard)/(admin)/ingredients/$ingredientId/': typeof privatedashboardadminIngredientsIngredientIdIndexRoute
  '/(private)/(dashboard)/(admin)/ingredients/create/': typeof privatedashboardadminIngredientsCreateIndexRoute
  '/(private)/(dashboard)/(admin)/products/$productId/': typeof privatedashboardadminProductsProductIdIndexRoute
  '/(private)/(dashboard)/(admin)/products/create/': typeof privatedashboardadminProductsCreateIndexRoute
  '/(private)/(dashboard)/(admin)/purchases/': typeof privatedashboardadminPurchasesIndexRoute
  '/(private)/(dashboard)/(admin)/purchases/create/': typeof privatedashboardadminPurchasesCreateIndexRoute
  '/(private)/(dashboard)/(admin)/purchases/$purchaseId/': typeof privatedashboardadminPurchasesPurchaseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/unauthorized'
    | '/login'
    | '/'
    | '/notifications'
    | '/api/auth/$'
    | '/orders/'
    | '/pos/'
    | '/tasks/'
    | '/settings/'
    | '/tasks/$taskId/'
    | '/tasks/create/'
    | '/employees/'
    | '/ingredients/'
    | '/products/'
    | '/inventory-reports/'
    | '/sales-reports/'
    | '/employees/$employeeId/'
    | '/employees/create/'
    | '/ingredients/$ingredientId/'
    | '/ingredients/create/'
    | '/products/$productId/'
    | '/products/create/'
    | '/purchases/'
    | '/purchases/create/'
    | '/purchases/$purchaseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/unauthorized'
    | '/login'
    | '/'
    | '/notifications'
    | '/api/auth/$'
    | '/orders'
    | '/pos'
    | '/tasks'
    | '/settings'
    | '/tasks/$taskId'
    | '/tasks/create'
    | '/employees'
    | '/ingredients'
    | '/products'
    | '/inventory-reports'
    | '/sales-reports'
    | '/employees/$employeeId'
    | '/employees/create'
    | '/ingredients/$ingredientId'
    | '/ingredients/create'
    | '/products/$productId'
    | '/products/create'
    | '/purchases'
    | '/purchases/create'
    | '/purchases/$purchaseId'
  id:
    | '__root__'
    | '/(private)'
    | '/(public)'
    | '/unauthorized'
    | '/(private)/(dashboard)'
    | '/(public)/login'
    | '/(public)/'
    | '/(private)/(dashboard)/(admin)'
    | '/(private)/(dashboard)/(supervisor)'
    | '/(private)/(dashboard)/settings'
    | '/(private)/(dashboard)/notifications'
    | '/api/auth/$'
    | '/(private)/orders/'
    | '/(private)/pos/'
    | '/(private)/tasks/'
    | '/(private)/(dashboard)/settings/'
    | '/(private)/tasks/$taskId/'
    | '/(private)/tasks/create/'
    | '/(private)/(dashboard)/(admin)/employees/'
    | '/(private)/(dashboard)/(admin)/ingredients/'
    | '/(private)/(dashboard)/(admin)/products/'
    | '/(private)/(dashboard)/(supervisor)/inventory-reports/'
    | '/(private)/(dashboard)/(supervisor)/sales-reports/'
    | '/(private)/(dashboard)/(admin)/employees/$employeeId/'
    | '/(private)/(dashboard)/(admin)/employees/create/'
    | '/(private)/(dashboard)/(admin)/ingredients/$ingredientId/'
    | '/(private)/(dashboard)/(admin)/ingredients/create/'
    | '/(private)/(dashboard)/(admin)/products/$productId/'
    | '/(private)/(dashboard)/(admin)/products/create/'
    | '/(private)/(dashboard)/(admin)/purchases/'
    | '/(private)/(dashboard)/(admin)/purchases/create/'
    | '/(private)/(dashboard)/(admin)/purchases/$purchaseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateRouteRoute: typeof privateRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(private)/(dashboard)': {
      id: '/(private)/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privatedashboardRouteRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/tasks/': {
      id: '/(private)/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof privateTasksIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/pos/': {
      id: '/(private)/pos/'
      path: '/pos'
      fullPath: '/pos/'
      preLoaderRoute: typeof privatePosIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/orders/': {
      id: '/(private)/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof privateOrdersIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/(dashboard)/notifications': {
      id: '/(private)/(dashboard)/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof privatedashboardNotificationsRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/(admin)': {
      id: '/(private)/(dashboard)/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privatedashboardadminRouteRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/(supervisor)': {
      id: '/(private)/(dashboard)/(supervisor)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privatedashboardsupervisorRouteRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/settings': {
      id: '/(private)/(dashboard)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof privatedashboardsettingsRouteRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/tasks/create/': {
      id: '/(private)/tasks/create/'
      path: '/tasks/create'
      fullPath: '/tasks/create/'
      preLoaderRoute: typeof privateTasksCreateIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/tasks/$taskId/': {
      id: '/(private)/tasks/$taskId/'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId/'
      preLoaderRoute: typeof privateTasksTaskIdIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/(dashboard)/settings/': {
      id: '/(private)/(dashboard)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof privatedashboardSettingsIndexRouteImport
      parentRoute: typeof privatedashboardsettingsRouteRoute
    }
    '/(private)/(dashboard)/(supervisor)/sales-reports/': {
      id: '/(private)/(dashboard)/(supervisor)/sales-reports/'
      path: '/sales-reports'
      fullPath: '/sales-reports/'
      preLoaderRoute: typeof privatedashboardsupervisorSalesReportsIndexRouteImport
      parentRoute: typeof privatedashboardsupervisorRouteRoute
    }
    '/(private)/(dashboard)/(supervisor)/inventory-reports/': {
      id: '/(private)/(dashboard)/(supervisor)/inventory-reports/'
      path: '/inventory-reports'
      fullPath: '/inventory-reports/'
      preLoaderRoute: typeof privatedashboardsupervisorInventoryReportsIndexRouteImport
      parentRoute: typeof privatedashboardsupervisorRouteRoute
    }
    '/(private)/(dashboard)/(admin)/products/': {
      id: '/(private)/(dashboard)/(admin)/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof privatedashboardadminProductsIndexRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/(admin)/ingredients/': {
      id: '/(private)/(dashboard)/(admin)/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof privatedashboardadminIngredientsIndexRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/(admin)/employees/': {
      id: '/(private)/(dashboard)/(admin)/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof privatedashboardadminEmployeesIndexRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/(admin)/products/create/': {
      id: '/(private)/(dashboard)/(admin)/products/create/'
      path: '/products/create'
      fullPath: '/products/create/'
      preLoaderRoute: typeof privatedashboardadminProductsCreateIndexRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/(admin)/products/$productId/': {
      id: '/(private)/(dashboard)/(admin)/products/$productId/'
      path: '/products/$productId'
      fullPath: '/products/$productId/'
      preLoaderRoute: typeof privatedashboardadminProductsProductIdIndexRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/(admin)/ingredients/create/': {
      id: '/(private)/(dashboard)/(admin)/ingredients/create/'
      path: '/ingredients/create'
      fullPath: '/ingredients/create/'
      preLoaderRoute: typeof privatedashboardadminIngredientsCreateIndexRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/(admin)/ingredients/$ingredientId/': {
      id: '/(private)/(dashboard)/(admin)/ingredients/$ingredientId/'
      path: '/ingredients/$ingredientId'
      fullPath: '/ingredients/$ingredientId/'
      preLoaderRoute: typeof privatedashboardadminIngredientsIngredientIdIndexRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/(admin)/employees/create/': {
      id: '/(private)/(dashboard)/(admin)/employees/create/'
      path: '/employees/create'
      fullPath: '/employees/create/'
      preLoaderRoute: typeof privatedashboardadminEmployeesCreateIndexRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/(admin)/employees/$employeeId/': {
      id: '/(private)/(dashboard)/(admin)/employees/$employeeId/'
      path: '/employees/$employeeId'
      fullPath: '/employees/$employeeId/'
      preLoaderRoute: typeof privatedashboardadminEmployeesEmployeeIdIndexRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/(admin)/purchases/': {
      id: '/(private)/(dashboard)/(admin)/purchases/'
      path: '/purchases'
      fullPath: '/purchases/'
      preLoaderRoute: typeof privatedashboardadminPurchasesIndexRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/(admin)/purchases/create/': {
      id: '/(private)/(dashboard)/(admin)/purchases/create/'
      path: '/purchases/create'
      fullPath: '/purchases/create/'
      preLoaderRoute: typeof privatedashboardadminPurchasesCreateIndexRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/(admin)/purchases/$purchaseId/': {
      id: '/(private)/(dashboard)/(admin)/purchases/$purchaseId/'
      path: '/purchases/$purchaseId'
      fullPath: '/purchases/$purchaseId/'
      preLoaderRoute: typeof privatedashboardadminPurchasesPurchaseIdIndexRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
  }
}

interface privatedashboardadminRouteRouteChildren {
  privatedashboardadminEmployeesIndexRoute: typeof privatedashboardadminEmployeesIndexRoute
  privatedashboardadminIngredientsIndexRoute: typeof privatedashboardadminIngredientsIndexRoute
  privatedashboardadminProductsIndexRoute: typeof privatedashboardadminProductsIndexRoute
  privatedashboardadminEmployeesEmployeeIdIndexRoute: typeof privatedashboardadminEmployeesEmployeeIdIndexRoute
  privatedashboardadminEmployeesCreateIndexRoute: typeof privatedashboardadminEmployeesCreateIndexRoute
  privatedashboardadminIngredientsIngredientIdIndexRoute: typeof privatedashboardadminIngredientsIngredientIdIndexRoute
  privatedashboardadminIngredientsCreateIndexRoute: typeof privatedashboardadminIngredientsCreateIndexRoute
  privatedashboardadminProductsProductIdIndexRoute: typeof privatedashboardadminProductsProductIdIndexRoute
  privatedashboardadminProductsCreateIndexRoute: typeof privatedashboardadminProductsCreateIndexRoute
  privatedashboardadminPurchasesIndexRoute: typeof privatedashboardadminPurchasesIndexRoute
  privatedashboardadminPurchasesCreateIndexRoute: typeof privatedashboardadminPurchasesCreateIndexRoute
  privatedashboardadminPurchasesPurchaseIdIndexRoute: typeof privatedashboardadminPurchasesPurchaseIdIndexRoute
}

const privatedashboardadminRouteRouteChildren: privatedashboardadminRouteRouteChildren =
  {
    privatedashboardadminEmployeesIndexRoute:
      privatedashboardadminEmployeesIndexRoute,
    privatedashboardadminIngredientsIndexRoute:
      privatedashboardadminIngredientsIndexRoute,
    privatedashboardadminProductsIndexRoute:
      privatedashboardadminProductsIndexRoute,
    privatedashboardadminEmployeesEmployeeIdIndexRoute:
      privatedashboardadminEmployeesEmployeeIdIndexRoute,
    privatedashboardadminEmployeesCreateIndexRoute:
      privatedashboardadminEmployeesCreateIndexRoute,
    privatedashboardadminIngredientsIngredientIdIndexRoute:
      privatedashboardadminIngredientsIngredientIdIndexRoute,
    privatedashboardadminIngredientsCreateIndexRoute:
      privatedashboardadminIngredientsCreateIndexRoute,
    privatedashboardadminProductsProductIdIndexRoute:
      privatedashboardadminProductsProductIdIndexRoute,
    privatedashboardadminProductsCreateIndexRoute:
      privatedashboardadminProductsCreateIndexRoute,
    privatedashboardadminPurchasesIndexRoute:
      privatedashboardadminPurchasesIndexRoute,
    privatedashboardadminPurchasesCreateIndexRoute:
      privatedashboardadminPurchasesCreateIndexRoute,
  }

const privatedashboardadminRouteRouteWithChildren =
  privatedashboardadminRouteRoute._addFileChildren(
    privatedashboardadminRouteRouteChildren,
  )

interface privatedashboardsupervisorRouteRouteChildren {
  privatedashboardsupervisorInventoryReportsIndexRoute: typeof privatedashboardsupervisorInventoryReportsIndexRoute
  privatedashboardsupervisorSalesReportsIndexRoute: typeof privatedashboardsupervisorSalesReportsIndexRoute
}

const privatedashboardsupervisorRouteRouteChildren: privatedashboardsupervisorRouteRouteChildren =
  {
    privatedashboardsupervisorInventoryReportsIndexRoute:
      privatedashboardsupervisorInventoryReportsIndexRoute,
    privatedashboardsupervisorSalesReportsIndexRoute:
      privatedashboardsupervisorSalesReportsIndexRoute,
  }

const privatedashboardsupervisorRouteRouteWithChildren =
  privatedashboardsupervisorRouteRoute._addFileChildren(
    privatedashboardsupervisorRouteRouteChildren,
  )

interface privatedashboardsettingsRouteRouteChildren {
  privatedashboardSettingsIndexRoute: typeof privatedashboardSettingsIndexRoute
}

const privatedashboardsettingsRouteRouteChildren: privatedashboardsettingsRouteRouteChildren =
  {
    privatedashboardSettingsIndexRoute: privatedashboardSettingsIndexRoute,
  }

const privatedashboardsettingsRouteRouteWithChildren =
  privatedashboardsettingsRouteRoute._addFileChildren(
    privatedashboardsettingsRouteRouteChildren,
  )

interface privatedashboardRouteRouteChildren {
  privatedashboardadminRouteRoute: typeof privatedashboardadminRouteRouteWithChildren
  privatedashboardsupervisorRouteRoute: typeof privatedashboardsupervisorRouteRouteWithChildren
  privatedashboardsettingsRouteRoute: typeof privatedashboardsettingsRouteRouteWithChildren
  privatedashboardNotificationsRoute: typeof privatedashboardNotificationsRoute
}

const privatedashboardRouteRouteChildren: privatedashboardRouteRouteChildren = {
  privatedashboardadminRouteRoute: privatedashboardadminRouteRouteWithChildren,
  privatedashboardsupervisorRouteRoute: privatedashboardsupervisorRouteRouteWithChildren,
  privatedashboardsettingsRouteRoute: privatedashboardsettingsRouteRouteWithChildren,
  privatedashboardNotificationsRoute: privatedashboardNotificationsRoute,
}

const privatedashboardRouteRouteWithChildren =
  privatedashboardRouteRoute._addFileChildren(
    privatedashboardRouteRouteChildren,
  )

interface privateRouteRouteChildren {
  privatedashboardRouteRoute: typeof privatedashboardRouteRouteWithChildren
  privateOrdersIndexRoute: typeof privateOrdersIndexRoute
  privatePosIndexRoute: typeof privatePosIndexRoute
  privateTasksIndexRoute: typeof privateTasksIndexRoute
  privateTasksTaskIdIndexRoute: typeof privateTasksTaskIdIndexRoute
  privateTasksCreateIndexRoute: typeof privateTasksCreateIndexRoute
}

const privateRouteRouteChildren: privateRouteRouteChildren = {
  privatedashboardRouteRoute: privatedashboardRouteRouteWithChildren,
  privateOrdersIndexRoute: privateOrdersIndexRoute,
  privatePosIndexRoute: privatePosIndexRoute,
  privateTasksIndexRoute: privateTasksIndexRoute,
  privateTasksTaskIdIndexRoute: privateTasksTaskIdIndexRoute,
  privateTasksCreateIndexRoute: privateTasksCreateIndexRoute,
}

const privateRouteRouteWithChildren = privateRouteRoute._addFileChildren(
  privateRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicLoginRoute: typeof publicLoginRoute
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicLoginRoute: publicLoginRoute,
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  privateRouteRoute: privateRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
