/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as privateRouteRouteImport } from './routes/(private)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicRegisterRouteImport } from './routes/(public)/register'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as publicForgotPasswordRouteImport } from './routes/(public)/forgot-password'
import { Route as privateBillingRouteImport } from './routes/(private)/billing'
import { Route as privatedashboardRouteRouteImport } from './routes/(private)/(dashboard)/route'
import { Route as SubscriptionReactivateIndexRouteImport } from './routes/subscription/reactivate/index'
import { Route as privateTasksIndexRouteImport } from './routes/(private)/tasks/index'
import { Route as privatePosIndexRouteImport } from './routes/(private)/pos/index'
import { Route as privateOrdersIndexRouteImport } from './routes/(private)/orders/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as publicRegisterBusinessSetupRouteImport } from './routes/(public)/register/business-setup'
import { Route as privatedashboardNotificationsRouteImport } from './routes/(private)/(dashboard)/notifications'
import { Route as privatedashboardDashboardRouteImport } from './routes/(private)/(dashboard)/dashboard'
import { Route as privatedashboardContactUsRouteImport } from './routes/(private)/(dashboard)/contact-us'
import { Route as privatedashboardSettingsRouteRouteImport } from './routes/(private)/(dashboard)/settings/route'
import { Route as privatedashboardBusinessRouteRouteImport } from './routes/(private)/(dashboard)/business/route'
import { Route as privatedashboardBillingRouteRouteImport } from './routes/(private)/(dashboard)/billing/route'
import { Route as privatedashboardAccountRouteRouteImport } from './routes/(private)/(dashboard)/account/route'
import { Route as privatedashboardsupervisorRouteRouteImport } from './routes/(private)/(dashboard)/(supervisor)/route'
import { Route as privatedashboardadminRouteRouteImport } from './routes/(private)/(dashboard)/(admin)/route'
import { Route as ApiCronDailyIndexRouteImport } from './routes/api/cron/daily/index'
import { Route as ApiBillingWebhookIndexRouteImport } from './routes/api/billing/webhook/index'
import { Route as privateTasksCreateIndexRouteImport } from './routes/(private)/tasks/create/index'
import { Route as privateTasksTaskIdIndexRouteImport } from './routes/(private)/tasks/$taskId/index'
import { Route as privatedashboardSettingsIndexRouteImport } from './routes/(private)/(dashboard)/settings/index'
import { Route as privatedashboardBusinessIndexRouteImport } from './routes/(private)/(dashboard)/business/index'
import { Route as privatedashboardBillingIndexRouteImport } from './routes/(private)/(dashboard)/billing/index'
import { Route as privatedashboardAccountIndexRouteImport } from './routes/(private)/(dashboard)/account/index'
import { Route as ApiBillingWebhookStripeRouteImport } from './routes/api/billing/webhook/stripe'
import { Route as privatedashboardSettingsComplianceRouteImport } from './routes/(private)/(dashboard)/settings/compliance'
import { Route as privatedashboardBillingPaymentMethodsRouteImport } from './routes/(private)/(dashboard)/business/subscription/payment-methods.tsx'
import { Route as privatedashboardBillingManualPaymentRouteImport } from './routes/(private)/(dashboard)/billing/manual-payment'
import { Route as privatedashboardadminPaymentApprovalsRouteImport } from './routes/(private)/(dashboard)/(admin)/payment-approvals'
import { Route as privatedashboardBusinessSuppliersRouteRouteImport } from './routes/(private)/(dashboard)/business/suppliers/route'
import { Route as privatedashboardBusinessSubscriptionRouteRouteImport } from './routes/(private)/(dashboard)/business/subscription/route'
import { Route as privatedashboardBusinessCustomersRouteRouteImport } from './routes/(private)/(dashboard)/business/customers/route'
import { Route as privatedashboardadminPreparationRouteRouteImport } from './routes/(private)/(dashboard)/(admin)/preparation/route'
import { Route as privatedashboardBusinessSuppliersIndexRouteImport } from './routes/(private)/(dashboard)/business/suppliers/index'
import { Route as privatedashboardBusinessSubscriptionIndexRouteImport } from './routes/(private)/(dashboard)/business/subscription/index'
import { Route as privatedashboardBusinessProfileIndexRouteImport } from './routes/(private)/(dashboard)/business/profile/index'
import { Route as privatedashboardBusinessPermissionsIndexRouteImport } from './routes/(private)/(dashboard)/business/permissions/index'
import { Route as privatedashboardBusinessCustomersIndexRouteImport } from './routes/(private)/(dashboard)/business/customers/index'
import { Route as privatedashboardBusinessCapabilitiesIndexRouteImport } from './routes/(private)/(dashboard)/business/capabilities/index'
import { Route as privatedashboardBusinessBranchesIndexRouteImport } from './routes/(private)/(dashboard)/business/branches/index'
import { Route as privatedashboardAccountSecurityIndexRouteImport } from './routes/(private)/(dashboard)/account/security/index'
import { Route as privatedashboardAccountPreferencesIndexRouteImport } from './routes/(private)/(dashboard)/account/preferences/index'
import { Route as privatedashboardsupervisorTransactionsIndexRouteImport } from './routes/(private)/(dashboard)/(supervisor)/transactions/index'
import { Route as privatedashboardsupervisorSalesReportsIndexRouteImport } from './routes/(private)/(dashboard)/(supervisor)/sales-reports/index'
import { Route as privatedashboardsupervisorOrderHistoryIndexRouteImport } from './routes/(private)/(dashboard)/(supervisor)/order-history/index'
import { Route as privatedashboardsupervisorInventoryReportsIndexRouteImport } from './routes/(private)/(dashboard)/(supervisor)/inventory-reports/index'
import { Route as privatedashboardadminPurchasesIndexRouteImport } from './routes/(private)/(dashboard)/(admin)/purchases/index'
import { Route as privatedashboardadminProductsIndexRouteImport } from './routes/(private)/(dashboard)/(admin)/products/index'
import { Route as privatedashboardadminPreparationIndexRouteImport } from './routes/(private)/(dashboard)/(admin)/preparation/index'
import { Route as privatedashboardadminIngredientsIndexRouteImport } from './routes/(private)/(dashboard)/(admin)/ingredients/index'
import { Route as privatedashboardadminEmployeesIndexRouteImport } from './routes/(private)/(dashboard)/(admin)/employees/index'
import { Route as privatedashboardadminPreparationHistoryRouteImport } from './routes/(private)/(dashboard)/(admin)/preparation/history'
import { Route as privatedashboardBusinessSubscriptionSuccessIndexRouteImport } from './routes/(private)/(dashboard)/business/subscription/success/index'
import { Route as privatedashboardBusinessSubscriptionQuotesIndexRouteImport } from './routes/(private)/(dashboard)/business/subscription/quotes/index'
import { Route as privatedashboardBusinessSubscriptionPricingIndexRouteImport } from './routes/(private)/(dashboard)/business/subscription/pricing/index'
import { Route as privatedashboardBusinessSubscriptionPlansIndexRouteImport } from './routes/(private)/(dashboard)/business/subscription/plans/index'
import { Route as privatedashboardBusinessSubscriptionInvoicesIndexRouteImport } from './routes/(private)/(dashboard)/business/subscription/invoices/index'
import { Route as privatedashboardBusinessSubscriptionCreditsIndexRouteImport } from './routes/(private)/(dashboard)/business/subscription/credits/index'
import { Route as privatedashboardBusinessPermissionsAuditIndexRouteImport } from './routes/(private)/(dashboard)/business/permissions/audit/index'
import { Route as privatedashboardsupervisorTransactionsTransactionIdIndexRouteImport } from './routes/(private)/(dashboard)/(supervisor)/transactions/$transactionId/index'
import { Route as privatedashboardsupervisorOrderHistoryOrderIdIndexRouteImport } from './routes/(private)/(dashboard)/(supervisor)/order-history/$orderId/index'
import { Route as privatedashboardadminPurchasesPurchaseIdIndexRouteImport } from './routes/(private)/(dashboard)/(admin)/purchases/$purchaseId/index'
import { Route as privatedashboardadminProductsCreateIndexRouteImport } from './routes/(private)/(dashboard)/(admin)/products/create/index'
import { Route as privatedashboardadminProductsProductIdIndexRouteImport } from './routes/(private)/(dashboard)/(admin)/products/$productId/index'
import { Route as privatedashboardadminIngredientsCreateIndexRouteImport } from './routes/(private)/(dashboard)/(admin)/ingredients/create/index'
import { Route as privatedashboardadminIngredientsIngredientIdIndexRouteImport } from './routes/(private)/(dashboard)/(admin)/ingredients/$ingredientId/index'
import { Route as privatedashboardadminEmployeesCreateIndexRouteImport } from './routes/(private)/(dashboard)/(admin)/employees/create/index'
import { Route as privatedashboardadminEmployeesEmployeeIdIndexRouteImport } from './routes/(private)/(dashboard)/(admin)/employees/$employeeId/index'
import { Route as privatedashboardBusinessSubscriptionQuotesQuoteIdIndexRouteImport } from './routes/(private)/(dashboard)/business/subscription/quotes/$quoteId/index'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateRouteRoute = privateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicRegisterRoute = publicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicForgotPasswordRoute = publicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => publicRouteRoute,
} as any)
const privateBillingRoute = privateBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => privateRouteRoute,
} as any)
const privatedashboardRouteRoute = privatedashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => privateRouteRoute,
} as any)
const SubscriptionReactivateIndexRoute =
  SubscriptionReactivateIndexRouteImport.update({
    id: '/subscription/reactivate/',
    path: '/subscription/reactivate/',
    getParentRoute: () => rootRouteImport,
  } as any)
const privateTasksIndexRoute = privateTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => privateRouteRoute,
} as any)
const privatePosIndexRoute = privatePosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateOrdersIndexRoute = privateOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => privateRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRegisterBusinessSetupRoute =
  publicRegisterBusinessSetupRouteImport.update({
    id: '/business-setup',
    path: '/business-setup',
    getParentRoute: () => publicRegisterRoute,
  } as any)
const privatedashboardNotificationsRoute =
  privatedashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardDashboardRoute =
  privatedashboardDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardContactUsRoute =
  privatedashboardContactUsRouteImport.update({
    id: '/contact-us',
    path: '/contact-us',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardSettingsRouteRoute =
  privatedashboardSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardBusinessRouteRoute =
  privatedashboardBusinessRouteRouteImport.update({
    id: '/business',
    path: '/business',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardBillingRouteRoute =
  privatedashboardBillingRouteRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardAccountRouteRoute =
  privatedashboardAccountRouteRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardsupervisorRouteRoute =
  privatedashboardsupervisorRouteRouteImport.update({
    id: '/(supervisor)',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const privatedashboardadminRouteRoute =
  privatedashboardadminRouteRouteImport.update({
    id: '/(admin)',
    getParentRoute: () => privatedashboardRouteRoute,
  } as any)
const ApiCronDailyIndexRoute = ApiCronDailyIndexRouteImport.update({
  id: '/api/cron/daily/',
  path: '/api/cron/daily/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingWebhookIndexRoute = ApiBillingWebhookIndexRouteImport.update({
  id: '/api/billing/webhook/',
  path: '/api/billing/webhook/',
  getParentRoute: () => rootRouteImport,
} as any)
const privateTasksCreateIndexRoute = privateTasksCreateIndexRouteImport.update({
  id: '/tasks/create/',
  path: '/tasks/create/',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateTasksTaskIdIndexRoute = privateTasksTaskIdIndexRouteImport.update({
  id: '/tasks/$taskId/',
  path: '/tasks/$taskId/',
  getParentRoute: () => privateRouteRoute,
} as any)
const privatedashboardSettingsIndexRoute =
  privatedashboardSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privatedashboardSettingsRouteRoute,
  } as any)
const privatedashboardBusinessIndexRoute =
  privatedashboardBusinessIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privatedashboardBusinessRouteRoute,
  } as any)
const privatedashboardBillingIndexRoute =
  privatedashboardBillingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privatedashboardBillingRouteRoute,
  } as any)
const privatedashboardAccountIndexRoute =
  privatedashboardAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privatedashboardAccountRouteRoute,
  } as any)
const ApiBillingWebhookStripeRoute = ApiBillingWebhookStripeRouteImport.update({
  id: '/api/billing/webhook/stripe',
  path: '/api/billing/webhook/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const privatedashboardSettingsComplianceRoute =
  privatedashboardSettingsComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => privatedashboardSettingsRouteRoute,
  } as any)
const privatedashboardBillingPaymentMethodsRoute =
  privatedashboardBillingPaymentMethodsRouteImport.update({
    id: '/payment-methods',
    path: '/payment-methods',
    getParentRoute: () => privatedashboardBillingRouteRoute,
  } as any)
const privatedashboardBillingManualPaymentRoute =
  privatedashboardBillingManualPaymentRouteImport.update({
    id: '/manual-payment',
    path: '/manual-payment',
    getParentRoute: () => privatedashboardBillingRouteRoute,
  } as any)
const privatedashboardadminPaymentApprovalsRoute =
  privatedashboardadminPaymentApprovalsRouteImport.update({
    id: '/payment-approvals',
    path: '/payment-approvals',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardBusinessSuppliersRouteRoute =
  privatedashboardBusinessSuppliersRouteRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => privatedashboardBusinessRouteRoute,
  } as any)
const privatedashboardBusinessSubscriptionRouteRoute =
  privatedashboardBusinessSubscriptionRouteRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => privatedashboardBusinessRouteRoute,
  } as any)
const privatedashboardBusinessCustomersRouteRoute =
  privatedashboardBusinessCustomersRouteRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => privatedashboardBusinessRouteRoute,
  } as any)
const privatedashboardadminPreparationRouteRoute =
  privatedashboardadminPreparationRouteRouteImport.update({
    id: '/preparation',
    path: '/preparation',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardBusinessSuppliersIndexRoute =
  privatedashboardBusinessSuppliersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privatedashboardBusinessSuppliersRouteRoute,
  } as any)
const privatedashboardBusinessSubscriptionIndexRoute =
  privatedashboardBusinessSubscriptionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privatedashboardBusinessSubscriptionRouteRoute,
  } as any)
const privatedashboardBusinessProfileIndexRoute =
  privatedashboardBusinessProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => privatedashboardBusinessRouteRoute,
  } as any)
const privatedashboardBusinessPermissionsIndexRoute =
  privatedashboardBusinessPermissionsIndexRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => privatedashboardBusinessRouteRoute,
  } as any)
const privatedashboardBusinessCustomersIndexRoute =
  privatedashboardBusinessCustomersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privatedashboardBusinessCustomersRouteRoute,
  } as any)
const privatedashboardBusinessCapabilitiesIndexRoute =
  privatedashboardBusinessCapabilitiesIndexRouteImport.update({
    id: '/capabilities/',
    path: '/capabilities/',
    getParentRoute: () => privatedashboardBusinessRouteRoute,
  } as any)
const privatedashboardBusinessBranchesIndexRoute =
  privatedashboardBusinessBranchesIndexRouteImport.update({
    id: '/branches/',
    path: '/branches/',
    getParentRoute: () => privatedashboardBusinessRouteRoute,
  } as any)
const privatedashboardAccountSecurityIndexRoute =
  privatedashboardAccountSecurityIndexRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => privatedashboardAccountRouteRoute,
  } as any)
const privatedashboardAccountPreferencesIndexRoute =
  privatedashboardAccountPreferencesIndexRouteImport.update({
    id: '/preferences/',
    path: '/preferences/',
    getParentRoute: () => privatedashboardAccountRouteRoute,
  } as any)
const privatedashboardsupervisorTransactionsIndexRoute =
  privatedashboardsupervisorTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => privatedashboardsupervisorRouteRoute,
  } as any)
const privatedashboardsupervisorSalesReportsIndexRoute =
  privatedashboardsupervisorSalesReportsIndexRouteImport.update({
    id: '/sales-reports/',
    path: '/sales-reports/',
    getParentRoute: () => privatedashboardsupervisorRouteRoute,
  } as any)
const privatedashboardsupervisorOrderHistoryIndexRoute =
  privatedashboardsupervisorOrderHistoryIndexRouteImport.update({
    id: '/order-history/',
    path: '/order-history/',
    getParentRoute: () => privatedashboardsupervisorRouteRoute,
  } as any)
const privatedashboardsupervisorInventoryReportsIndexRoute =
  privatedashboardsupervisorInventoryReportsIndexRouteImport.update({
    id: '/inventory-reports/',
    path: '/inventory-reports/',
    getParentRoute: () => privatedashboardsupervisorRouteRoute,
  } as any)
const privatedashboardadminPurchasesIndexRoute =
  privatedashboardadminPurchasesIndexRouteImport.update({
    id: '/purchases/',
    path: '/purchases/',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardadminProductsIndexRoute =
  privatedashboardadminProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardadminPreparationIndexRoute =
  privatedashboardadminPreparationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privatedashboardadminPreparationRouteRoute,
  } as any)
const privatedashboardadminIngredientsIndexRoute =
  privatedashboardadminIngredientsIndexRouteImport.update({
    id: '/ingredients/',
    path: '/ingredients/',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardadminEmployeesIndexRoute =
  privatedashboardadminEmployeesIndexRouteImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardadminPreparationHistoryRoute =
  privatedashboardadminPreparationHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => privatedashboardadminPreparationRouteRoute,
  } as any)
const privatedashboardBusinessSubscriptionSuccessIndexRoute =
  privatedashboardBusinessSubscriptionSuccessIndexRouteImport.update({
    id: '/success/',
    path: '/success/',
    getParentRoute: () => privatedashboardBusinessSubscriptionRouteRoute,
  } as any)
const privatedashboardBusinessSubscriptionQuotesIndexRoute =
  privatedashboardBusinessSubscriptionQuotesIndexRouteImport.update({
    id: '/quotes/',
    path: '/quotes/',
    getParentRoute: () => privatedashboardBusinessSubscriptionRouteRoute,
  } as any)
const privatedashboardBusinessSubscriptionPricingIndexRoute =
  privatedashboardBusinessSubscriptionPricingIndexRouteImport.update({
    id: '/pricing/',
    path: '/pricing/',
    getParentRoute: () => privatedashboardBusinessSubscriptionRouteRoute,
  } as any)
const privatedashboardBusinessSubscriptionPlansIndexRoute =
  privatedashboardBusinessSubscriptionPlansIndexRouteImport.update({
    id: '/plans/',
    path: '/plans/',
    getParentRoute: () => privatedashboardBusinessSubscriptionRouteRoute,
  } as any)
const privatedashboardBusinessSubscriptionInvoicesIndexRoute =
  privatedashboardBusinessSubscriptionInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => privatedashboardBusinessSubscriptionRouteRoute,
  } as any)
const privatedashboardBusinessSubscriptionCreditsIndexRoute =
  privatedashboardBusinessSubscriptionCreditsIndexRouteImport.update({
    id: '/credits/',
    path: '/credits/',
    getParentRoute: () => privatedashboardBusinessSubscriptionRouteRoute,
  } as any)
const privatedashboardBusinessPermissionsAuditIndexRoute =
  privatedashboardBusinessPermissionsAuditIndexRouteImport.update({
    id: '/permissions/audit/',
    path: '/permissions/audit/',
    getParentRoute: () => privatedashboardBusinessRouteRoute,
  } as any)
const privatedashboardsupervisorTransactionsTransactionIdIndexRoute =
  privatedashboardsupervisorTransactionsTransactionIdIndexRouteImport.update({
    id: '/transactions/$transactionId/',
    path: '/transactions/$transactionId/',
    getParentRoute: () => privatedashboardsupervisorRouteRoute,
  } as any)
const privatedashboardsupervisorOrderHistoryOrderIdIndexRoute =
  privatedashboardsupervisorOrderHistoryOrderIdIndexRouteImport.update({
    id: '/order-history/$orderId/',
    path: '/order-history/$orderId/',
    getParentRoute: () => privatedashboardsupervisorRouteRoute,
  } as any)
const privatedashboardadminPurchasesPurchaseIdIndexRoute =
  privatedashboardadminPurchasesPurchaseIdIndexRouteImport.update({
    id: '/purchases/$purchaseId/',
    path: '/purchases/$purchaseId/',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardadminProductsCreateIndexRoute =
  privatedashboardadminProductsCreateIndexRouteImport.update({
    id: '/products/create/',
    path: '/products/create/',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardadminProductsProductIdIndexRoute =
  privatedashboardadminProductsProductIdIndexRouteImport.update({
    id: '/products/$productId/',
    path: '/products/$productId/',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardadminIngredientsCreateIndexRoute =
  privatedashboardadminIngredientsCreateIndexRouteImport.update({
    id: '/ingredients/create/',
    path: '/ingredients/create/',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardadminIngredientsIngredientIdIndexRoute =
  privatedashboardadminIngredientsIngredientIdIndexRouteImport.update({
    id: '/ingredients/$ingredientId/',
    path: '/ingredients/$ingredientId/',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardadminEmployeesCreateIndexRoute =
  privatedashboardadminEmployeesCreateIndexRouteImport.update({
    id: '/employees/create/',
    path: '/employees/create/',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardadminEmployeesEmployeeIdIndexRoute =
  privatedashboardadminEmployeesEmployeeIdIndexRouteImport.update({
    id: '/employees/$employeeId/',
    path: '/employees/$employeeId/',
    getParentRoute: () => privatedashboardadminRouteRoute,
  } as any)
const privatedashboardBusinessSubscriptionQuotesQuoteIdIndexRoute =
  privatedashboardBusinessSubscriptionQuotesQuoteIdIndexRouteImport.update({
    id: '/quotes/$quoteId/',
    path: '/quotes/$quoteId/',
    getParentRoute: () => privatedashboardBusinessSubscriptionRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/billing': typeof privatedashboardBillingRouteRouteWithChildren
  '/forgot-password': typeof publicForgotPasswordRoute
  '/login': typeof publicLoginRoute
  '/register': typeof publicRegisterRouteWithChildren
  '/': typeof publicIndexRoute
  '/account': typeof privatedashboardAccountRouteRouteWithChildren
  '/business': typeof privatedashboardBusinessRouteRouteWithChildren
  '/settings': typeof privatedashboardSettingsRouteRouteWithChildren
  '/contact-us': typeof privatedashboardContactUsRoute
  '/dashboard': typeof privatedashboardDashboardRoute
  '/notifications': typeof privatedashboardNotificationsRoute
  '/register/business-setup': typeof publicRegisterBusinessSetupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/orders/': typeof privateOrdersIndexRoute
  '/pos/': typeof privatePosIndexRoute
  '/tasks/': typeof privateTasksIndexRoute
  '/subscription/reactivate/': typeof SubscriptionReactivateIndexRoute
  '/preparation': typeof privatedashboardadminPreparationRouteRouteWithChildren
  '/business/customers': typeof privatedashboardBusinessCustomersRouteRouteWithChildren
  '/business/subscription': typeof privatedashboardBusinessSubscriptionRouteRouteWithChildren
  '/business/suppliers': typeof privatedashboardBusinessSuppliersRouteRouteWithChildren
  '/payment-approvals': typeof privatedashboardadminPaymentApprovalsRoute
  '/billing/manual-payment': typeof privatedashboardBillingManualPaymentRoute
  '/billing/payment-methods': typeof privatedashboardBillingPaymentMethodsRoute
  '/settings/compliance': typeof privatedashboardSettingsComplianceRoute
  '/api/billing/webhook/stripe': typeof ApiBillingWebhookStripeRoute
  '/account/': typeof privatedashboardAccountIndexRoute
  '/billing/': typeof privatedashboardBillingIndexRoute
  '/business/': typeof privatedashboardBusinessIndexRoute
  '/settings/': typeof privatedashboardSettingsIndexRoute
  '/tasks/$taskId/': typeof privateTasksTaskIdIndexRoute
  '/tasks/create/': typeof privateTasksCreateIndexRoute
  '/api/billing/webhook/': typeof ApiBillingWebhookIndexRoute
  '/api/cron/daily/': typeof ApiCronDailyIndexRoute
  '/preparation/history': typeof privatedashboardadminPreparationHistoryRoute
  '/employees/': typeof privatedashboardadminEmployeesIndexRoute
  '/ingredients/': typeof privatedashboardadminIngredientsIndexRoute
  '/preparation/': typeof privatedashboardadminPreparationIndexRoute
  '/products/': typeof privatedashboardadminProductsIndexRoute
  '/purchases/': typeof privatedashboardadminPurchasesIndexRoute
  '/inventory-reports/': typeof privatedashboardsupervisorInventoryReportsIndexRoute
  '/order-history/': typeof privatedashboardsupervisorOrderHistoryIndexRoute
  '/sales-reports/': typeof privatedashboardsupervisorSalesReportsIndexRoute
  '/transactions/': typeof privatedashboardsupervisorTransactionsIndexRoute
  '/account/preferences/': typeof privatedashboardAccountPreferencesIndexRoute
  '/account/security/': typeof privatedashboardAccountSecurityIndexRoute
  '/business/branches/': typeof privatedashboardBusinessBranchesIndexRoute
  '/business/capabilities/': typeof privatedashboardBusinessCapabilitiesIndexRoute
  '/business/customers/': typeof privatedashboardBusinessCustomersIndexRoute
  '/business/permissions/': typeof privatedashboardBusinessPermissionsIndexRoute
  '/business/profile/': typeof privatedashboardBusinessProfileIndexRoute
  '/business/subscription/': typeof privatedashboardBusinessSubscriptionIndexRoute
  '/business/suppliers/': typeof privatedashboardBusinessSuppliersIndexRoute
  '/employees/$employeeId/': typeof privatedashboardadminEmployeesEmployeeIdIndexRoute
  '/employees/create/': typeof privatedashboardadminEmployeesCreateIndexRoute
  '/ingredients/$ingredientId/': typeof privatedashboardadminIngredientsIngredientIdIndexRoute
  '/ingredients/create/': typeof privatedashboardadminIngredientsCreateIndexRoute
  '/products/$productId/': typeof privatedashboardadminProductsProductIdIndexRoute
  '/products/create/': typeof privatedashboardadminProductsCreateIndexRoute
  '/purchases/$purchaseId/': typeof privatedashboardadminPurchasesPurchaseIdIndexRoute
  '/order-history/$orderId/': typeof privatedashboardsupervisorOrderHistoryOrderIdIndexRoute
  '/transactions/$transactionId/': typeof privatedashboardsupervisorTransactionsTransactionIdIndexRoute
  '/business/permissions/audit/': typeof privatedashboardBusinessPermissionsAuditIndexRoute
  '/business/subscription/credits/': typeof privatedashboardBusinessSubscriptionCreditsIndexRoute
  '/business/subscription/invoices/': typeof privatedashboardBusinessSubscriptionInvoicesIndexRoute
  '/business/subscription/plans/': typeof privatedashboardBusinessSubscriptionPlansIndexRoute
  '/business/subscription/pricing/': typeof privatedashboardBusinessSubscriptionPricingIndexRoute
  '/business/subscription/quotes/': typeof privatedashboardBusinessSubscriptionQuotesIndexRoute
  '/business/subscription/success/': typeof privatedashboardBusinessSubscriptionSuccessIndexRoute
  '/business/subscription/quotes/$quoteId/': typeof privatedashboardBusinessSubscriptionQuotesQuoteIdIndexRoute
}
export interface FileRoutesByTo {
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/billing': typeof privatedashboardBillingIndexRoute
  '/forgot-password': typeof publicForgotPasswordRoute
  '/login': typeof publicLoginRoute
  '/register': typeof publicRegisterRouteWithChildren
  '/': typeof publicIndexRoute
  '/contact-us': typeof privatedashboardContactUsRoute
  '/dashboard': typeof privatedashboardDashboardRoute
  '/notifications': typeof privatedashboardNotificationsRoute
  '/register/business-setup': typeof publicRegisterBusinessSetupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/orders': typeof privateOrdersIndexRoute
  '/pos': typeof privatePosIndexRoute
  '/tasks': typeof privateTasksIndexRoute
  '/subscription/reactivate': typeof SubscriptionReactivateIndexRoute
  '/payment-approvals': typeof privatedashboardadminPaymentApprovalsRoute
  '/billing/manual-payment': typeof privatedashboardBillingManualPaymentRoute
  '/billing/payment-methods': typeof privatedashboardBillingPaymentMethodsRoute
  '/settings/compliance': typeof privatedashboardSettingsComplianceRoute
  '/api/billing/webhook/stripe': typeof ApiBillingWebhookStripeRoute
  '/account': typeof privatedashboardAccountIndexRoute
  '/business': typeof privatedashboardBusinessIndexRoute
  '/settings': typeof privatedashboardSettingsIndexRoute
  '/tasks/$taskId': typeof privateTasksTaskIdIndexRoute
  '/tasks/create': typeof privateTasksCreateIndexRoute
  '/api/billing/webhook': typeof ApiBillingWebhookIndexRoute
  '/api/cron/daily': typeof ApiCronDailyIndexRoute
  '/preparation/history': typeof privatedashboardadminPreparationHistoryRoute
  '/employees': typeof privatedashboardadminEmployeesIndexRoute
  '/ingredients': typeof privatedashboardadminIngredientsIndexRoute
  '/preparation': typeof privatedashboardadminPreparationIndexRoute
  '/products': typeof privatedashboardadminProductsIndexRoute
  '/purchases': typeof privatedashboardadminPurchasesIndexRoute
  '/inventory-reports': typeof privatedashboardsupervisorInventoryReportsIndexRoute
  '/order-history': typeof privatedashboardsupervisorOrderHistoryIndexRoute
  '/sales-reports': typeof privatedashboardsupervisorSalesReportsIndexRoute
  '/transactions': typeof privatedashboardsupervisorTransactionsIndexRoute
  '/account/preferences': typeof privatedashboardAccountPreferencesIndexRoute
  '/account/security': typeof privatedashboardAccountSecurityIndexRoute
  '/business/branches': typeof privatedashboardBusinessBranchesIndexRoute
  '/business/capabilities': typeof privatedashboardBusinessCapabilitiesIndexRoute
  '/business/customers': typeof privatedashboardBusinessCustomersIndexRoute
  '/business/permissions': typeof privatedashboardBusinessPermissionsIndexRoute
  '/business/profile': typeof privatedashboardBusinessProfileIndexRoute
  '/business/subscription': typeof privatedashboardBusinessSubscriptionIndexRoute
  '/business/suppliers': typeof privatedashboardBusinessSuppliersIndexRoute
  '/employees/$employeeId': typeof privatedashboardadminEmployeesEmployeeIdIndexRoute
  '/employees/create': typeof privatedashboardadminEmployeesCreateIndexRoute
  '/ingredients/$ingredientId': typeof privatedashboardadminIngredientsIngredientIdIndexRoute
  '/ingredients/create': typeof privatedashboardadminIngredientsCreateIndexRoute
  '/products/$productId': typeof privatedashboardadminProductsProductIdIndexRoute
  '/products/create': typeof privatedashboardadminProductsCreateIndexRoute
  '/purchases/$purchaseId': typeof privatedashboardadminPurchasesPurchaseIdIndexRoute
  '/order-history/$orderId': typeof privatedashboardsupervisorOrderHistoryOrderIdIndexRoute
  '/transactions/$transactionId': typeof privatedashboardsupervisorTransactionsTransactionIdIndexRoute
  '/business/permissions/audit': typeof privatedashboardBusinessPermissionsAuditIndexRoute
  '/business/subscription/credits': typeof privatedashboardBusinessSubscriptionCreditsIndexRoute
  '/business/subscription/invoices': typeof privatedashboardBusinessSubscriptionInvoicesIndexRoute
  '/business/subscription/plans': typeof privatedashboardBusinessSubscriptionPlansIndexRoute
  '/business/subscription/pricing': typeof privatedashboardBusinessSubscriptionPricingIndexRoute
  '/business/subscription/quotes': typeof privatedashboardBusinessSubscriptionQuotesIndexRoute
  '/business/subscription/success': typeof privatedashboardBusinessSubscriptionSuccessIndexRoute
  '/business/subscription/quotes/$quoteId': typeof privatedashboardBusinessSubscriptionQuotesQuoteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(private)': typeof privateRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/(private)/(dashboard)': typeof privatedashboardRouteRouteWithChildren
  '/(private)/billing': typeof privateBillingRoute
  '/(public)/forgot-password': typeof publicForgotPasswordRoute
  '/(public)/login': typeof publicLoginRoute
  '/(public)/register': typeof publicRegisterRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(private)/(dashboard)/(admin)': typeof privatedashboardadminRouteRouteWithChildren
  '/(private)/(dashboard)/(supervisor)': typeof privatedashboardsupervisorRouteRouteWithChildren
  '/(private)/(dashboard)/account': typeof privatedashboardAccountRouteRouteWithChildren
  '/(private)/(dashboard)/billing': typeof privatedashboardBillingRouteRouteWithChildren
  '/(private)/(dashboard)/business': typeof privatedashboardBusinessRouteRouteWithChildren
  '/(private)/(dashboard)/settings': typeof privatedashboardSettingsRouteRouteWithChildren
  '/(private)/(dashboard)/contact-us': typeof privatedashboardContactUsRoute
  '/(private)/(dashboard)/dashboard': typeof privatedashboardDashboardRoute
  '/(private)/(dashboard)/notifications': typeof privatedashboardNotificationsRoute
  '/(public)/register/business-setup': typeof publicRegisterBusinessSetupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(private)/orders/': typeof privateOrdersIndexRoute
  '/(private)/pos/': typeof privatePosIndexRoute
  '/(private)/tasks/': typeof privateTasksIndexRoute
  '/subscription/reactivate/': typeof SubscriptionReactivateIndexRoute
  '/(private)/(dashboard)/(admin)/preparation': typeof privatedashboardadminPreparationRouteRouteWithChildren
  '/(private)/(dashboard)/business/customers': typeof privatedashboardBusinessCustomersRouteRouteWithChildren
  '/(private)/(dashboard)/business/subscription': typeof privatedashboardBusinessSubscriptionRouteRouteWithChildren
  '/(private)/(dashboard)/business/suppliers': typeof privatedashboardBusinessSuppliersRouteRouteWithChildren
  '/(private)/(dashboard)/(admin)/payment-approvals': typeof privatedashboardadminPaymentApprovalsRoute
  '/(private)/(dashboard)/billing/manual-payment': typeof privatedashboardBillingManualPaymentRoute
  '/(private)/(dashboard)/billing/payment-methods': typeof privatedashboardBillingPaymentMethodsRoute
  '/(private)/(dashboard)/settings/compliance': typeof privatedashboardSettingsComplianceRoute
  '/api/billing/webhook/stripe': typeof ApiBillingWebhookStripeRoute
  '/(private)/(dashboard)/account/': typeof privatedashboardAccountIndexRoute
  '/(private)/(dashboard)/billing/': typeof privatedashboardBillingIndexRoute
  '/(private)/(dashboard)/business/': typeof privatedashboardBusinessIndexRoute
  '/(private)/(dashboard)/settings/': typeof privatedashboardSettingsIndexRoute
  '/(private)/tasks/$taskId/': typeof privateTasksTaskIdIndexRoute
  '/(private)/tasks/create/': typeof privateTasksCreateIndexRoute
  '/api/billing/webhook/': typeof ApiBillingWebhookIndexRoute
  '/api/cron/daily/': typeof ApiCronDailyIndexRoute
  '/(private)/(dashboard)/(admin)/preparation/history': typeof privatedashboardadminPreparationHistoryRoute
  '/(private)/(dashboard)/(admin)/employees/': typeof privatedashboardadminEmployeesIndexRoute
  '/(private)/(dashboard)/(admin)/ingredients/': typeof privatedashboardadminIngredientsIndexRoute
  '/(private)/(dashboard)/(admin)/preparation/': typeof privatedashboardadminPreparationIndexRoute
  '/(private)/(dashboard)/(admin)/products/': typeof privatedashboardadminProductsIndexRoute
  '/(private)/(dashboard)/(admin)/purchases/': typeof privatedashboardadminPurchasesIndexRoute
  '/(private)/(dashboard)/(supervisor)/inventory-reports/': typeof privatedashboardsupervisorInventoryReportsIndexRoute
  '/(private)/(dashboard)/(supervisor)/order-history/': typeof privatedashboardsupervisorOrderHistoryIndexRoute
  '/(private)/(dashboard)/(supervisor)/sales-reports/': typeof privatedashboardsupervisorSalesReportsIndexRoute
  '/(private)/(dashboard)/(supervisor)/transactions/': typeof privatedashboardsupervisorTransactionsIndexRoute
  '/(private)/(dashboard)/account/preferences/': typeof privatedashboardAccountPreferencesIndexRoute
  '/(private)/(dashboard)/account/security/': typeof privatedashboardAccountSecurityIndexRoute
  '/(private)/(dashboard)/business/branches/': typeof privatedashboardBusinessBranchesIndexRoute
  '/(private)/(dashboard)/business/capabilities/': typeof privatedashboardBusinessCapabilitiesIndexRoute
  '/(private)/(dashboard)/business/customers/': typeof privatedashboardBusinessCustomersIndexRoute
  '/(private)/(dashboard)/business/permissions/': typeof privatedashboardBusinessPermissionsIndexRoute
  '/(private)/(dashboard)/business/profile/': typeof privatedashboardBusinessProfileIndexRoute
  '/(private)/(dashboard)/business/subscription/': typeof privatedashboardBusinessSubscriptionIndexRoute
  '/(private)/(dashboard)/business/suppliers/': typeof privatedashboardBusinessSuppliersIndexRoute
  '/(private)/(dashboard)/(admin)/employees/$employeeId/': typeof privatedashboardadminEmployeesEmployeeIdIndexRoute
  '/(private)/(dashboard)/(admin)/employees/create/': typeof privatedashboardadminEmployeesCreateIndexRoute
  '/(private)/(dashboard)/(admin)/ingredients/$ingredientId/': typeof privatedashboardadminIngredientsIngredientIdIndexRoute
  '/(private)/(dashboard)/(admin)/ingredients/create/': typeof privatedashboardadminIngredientsCreateIndexRoute
  '/(private)/(dashboard)/(admin)/products/$productId/': typeof privatedashboardadminProductsProductIdIndexRoute
  '/(private)/(dashboard)/(admin)/products/create/': typeof privatedashboardadminProductsCreateIndexRoute
  '/(private)/(dashboard)/(admin)/purchases/$purchaseId/': typeof privatedashboardadminPurchasesPurchaseIdIndexRoute
  '/(private)/(dashboard)/(supervisor)/order-history/$orderId/': typeof privatedashboardsupervisorOrderHistoryOrderIdIndexRoute
  '/(private)/(dashboard)/(supervisor)/transactions/$transactionId/': typeof privatedashboardsupervisorTransactionsTransactionIdIndexRoute
  '/(private)/(dashboard)/business/permissions/audit/': typeof privatedashboardBusinessPermissionsAuditIndexRoute
  '/(private)/(dashboard)/business/subscription/credits/': typeof privatedashboardBusinessSubscriptionCreditsIndexRoute
  '/(private)/(dashboard)/business/subscription/invoices/': typeof privatedashboardBusinessSubscriptionInvoicesIndexRoute
  '/(private)/(dashboard)/business/subscription/plans/': typeof privatedashboardBusinessSubscriptionPlansIndexRoute
  '/(private)/(dashboard)/business/subscription/pricing/': typeof privatedashboardBusinessSubscriptionPricingIndexRoute
  '/(private)/(dashboard)/business/subscription/quotes/': typeof privatedashboardBusinessSubscriptionQuotesIndexRoute
  '/(private)/(dashboard)/business/subscription/success/': typeof privatedashboardBusinessSubscriptionSuccessIndexRoute
  '/(private)/(dashboard)/business/subscription/quotes/$quoteId/': typeof privatedashboardBusinessSubscriptionQuotesQuoteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/privacy'
    | '/terms'
    | '/unauthorized'
    | '/billing'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/'
    | '/account'
    | '/business'
    | '/settings'
    | '/contact-us'
    | '/dashboard'
    | '/notifications'
    | '/register/business-setup'
    | '/api/auth/$'
    | '/orders/'
    | '/pos/'
    | '/tasks/'
    | '/subscription/reactivate/'
    | '/preparation'
    | '/business/customers'
    | '/business/subscription'
    | '/business/suppliers'
    | '/payment-approvals'
    | '/billing/manual-payment'
    | '/billing/payment-methods'
    | '/settings/compliance'
    | '/api/billing/webhook/stripe'
    | '/account/'
    | '/billing/'
    | '/business/'
    | '/settings/'
    | '/tasks/$taskId/'
    | '/tasks/create/'
    | '/api/billing/webhook/'
    | '/api/cron/daily/'
    | '/preparation/history'
    | '/employees/'
    | '/ingredients/'
    | '/preparation/'
    | '/products/'
    | '/purchases/'
    | '/inventory-reports/'
    | '/order-history/'
    | '/sales-reports/'
    | '/transactions/'
    | '/account/preferences/'
    | '/account/security/'
    | '/business/branches/'
    | '/business/capabilities/'
    | '/business/customers/'
    | '/business/permissions/'
    | '/business/profile/'
    | '/business/subscription/'
    | '/business/suppliers/'
    | '/employees/$employeeId/'
    | '/employees/create/'
    | '/ingredients/$ingredientId/'
    | '/ingredients/create/'
    | '/products/$productId/'
    | '/products/create/'
    | '/purchases/$purchaseId/'
    | '/order-history/$orderId/'
    | '/transactions/$transactionId/'
    | '/business/permissions/audit/'
    | '/business/subscription/credits/'
    | '/business/subscription/invoices/'
    | '/business/subscription/plans/'
    | '/business/subscription/pricing/'
    | '/business/subscription/quotes/'
    | '/business/subscription/success/'
    | '/business/subscription/quotes/$quoteId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/privacy'
    | '/terms'
    | '/unauthorized'
    | '/billing'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/'
    | '/contact-us'
    | '/dashboard'
    | '/notifications'
    | '/register/business-setup'
    | '/api/auth/$'
    | '/orders'
    | '/pos'
    | '/tasks'
    | '/subscription/reactivate'
    | '/payment-approvals'
    | '/billing/manual-payment'
    | '/billing/payment-methods'
    | '/settings/compliance'
    | '/api/billing/webhook/stripe'
    | '/account'
    | '/business'
    | '/settings'
    | '/tasks/$taskId'
    | '/tasks/create'
    | '/api/billing/webhook'
    | '/api/cron/daily'
    | '/preparation/history'
    | '/employees'
    | '/ingredients'
    | '/preparation'
    | '/products'
    | '/purchases'
    | '/inventory-reports'
    | '/order-history'
    | '/sales-reports'
    | '/transactions'
    | '/account/preferences'
    | '/account/security'
    | '/business/branches'
    | '/business/capabilities'
    | '/business/customers'
    | '/business/permissions'
    | '/business/profile'
    | '/business/subscription'
    | '/business/suppliers'
    | '/employees/$employeeId'
    | '/employees/create'
    | '/ingredients/$ingredientId'
    | '/ingredients/create'
    | '/products/$productId'
    | '/products/create'
    | '/purchases/$purchaseId'
    | '/order-history/$orderId'
    | '/transactions/$transactionId'
    | '/business/permissions/audit'
    | '/business/subscription/credits'
    | '/business/subscription/invoices'
    | '/business/subscription/plans'
    | '/business/subscription/pricing'
    | '/business/subscription/quotes'
    | '/business/subscription/success'
    | '/business/subscription/quotes/$quoteId'
  id:
    | '__root__'
    | '/(private)'
    | '/(public)'
    | '/privacy'
    | '/terms'
    | '/unauthorized'
    | '/(private)/(dashboard)'
    | '/(private)/billing'
    | '/(public)/forgot-password'
    | '/(public)/login'
    | '/(public)/register'
    | '/(public)/'
    | '/(private)/(dashboard)/(admin)'
    | '/(private)/(dashboard)/(supervisor)'
    | '/(private)/(dashboard)/account'
    | '/(private)/(dashboard)/billing'
    | '/(private)/(dashboard)/business'
    | '/(private)/(dashboard)/settings'
    | '/(private)/(dashboard)/contact-us'
    | '/(private)/(dashboard)/dashboard'
    | '/(private)/(dashboard)/notifications'
    | '/(public)/register/business-setup'
    | '/api/auth/$'
    | '/(private)/orders/'
    | '/(private)/pos/'
    | '/(private)/tasks/'
    | '/subscription/reactivate/'
    | '/(private)/(dashboard)/(admin)/preparation'
    | '/(private)/(dashboard)/business/customers'
    | '/(private)/(dashboard)/business/subscription'
    | '/(private)/(dashboard)/business/suppliers'
    | '/(private)/(dashboard)/(admin)/payment-approvals'
    | '/(private)/(dashboard)/billing/manual-payment'
    | '/(private)/(dashboard)/billing/payment-methods'
    | '/(private)/(dashboard)/settings/compliance'
    | '/api/billing/webhook/stripe'
    | '/(private)/(dashboard)/account/'
    | '/(private)/(dashboard)/billing/'
    | '/(private)/(dashboard)/business/'
    | '/(private)/(dashboard)/settings/'
    | '/(private)/tasks/$taskId/'
    | '/(private)/tasks/create/'
    | '/api/billing/webhook/'
    | '/api/cron/daily/'
    | '/(private)/(dashboard)/(admin)/preparation/history'
    | '/(private)/(dashboard)/(admin)/employees/'
    | '/(private)/(dashboard)/(admin)/ingredients/'
    | '/(private)/(dashboard)/(admin)/preparation/'
    | '/(private)/(dashboard)/(admin)/products/'
    | '/(private)/(dashboard)/(admin)/purchases/'
    | '/(private)/(dashboard)/(supervisor)/inventory-reports/'
    | '/(private)/(dashboard)/(supervisor)/order-history/'
    | '/(private)/(dashboard)/(supervisor)/sales-reports/'
    | '/(private)/(dashboard)/(supervisor)/transactions/'
    | '/(private)/(dashboard)/account/preferences/'
    | '/(private)/(dashboard)/account/security/'
    | '/(private)/(dashboard)/business/branches/'
    | '/(private)/(dashboard)/business/capabilities/'
    | '/(private)/(dashboard)/business/customers/'
    | '/(private)/(dashboard)/business/permissions/'
    | '/(private)/(dashboard)/business/profile/'
    | '/(private)/(dashboard)/business/subscription/'
    | '/(private)/(dashboard)/business/suppliers/'
    | '/(private)/(dashboard)/(admin)/employees/$employeeId/'
    | '/(private)/(dashboard)/(admin)/employees/create/'
    | '/(private)/(dashboard)/(admin)/ingredients/$ingredientId/'
    | '/(private)/(dashboard)/(admin)/ingredients/create/'
    | '/(private)/(dashboard)/(admin)/products/$productId/'
    | '/(private)/(dashboard)/(admin)/products/create/'
    | '/(private)/(dashboard)/(admin)/purchases/$purchaseId/'
    | '/(private)/(dashboard)/(supervisor)/order-history/$orderId/'
    | '/(private)/(dashboard)/(supervisor)/transactions/$transactionId/'
    | '/(private)/(dashboard)/business/permissions/audit/'
    | '/(private)/(dashboard)/business/subscription/credits/'
    | '/(private)/(dashboard)/business/subscription/invoices/'
    | '/(private)/(dashboard)/business/subscription/plans/'
    | '/(private)/(dashboard)/business/subscription/pricing/'
    | '/(private)/(dashboard)/business/subscription/quotes/'
    | '/(private)/(dashboard)/business/subscription/success/'
    | '/(private)/(dashboard)/business/subscription/quotes/$quoteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateRouteRoute: typeof privateRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  SubscriptionReactivateIndexRoute: typeof SubscriptionReactivateIndexRoute
  ApiBillingWebhookStripeRoute: typeof ApiBillingWebhookStripeRoute
  ApiBillingWebhookIndexRoute: typeof ApiBillingWebhookIndexRoute
  ApiCronDailyIndexRoute: typeof ApiCronDailyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/register': {
      id: '/(public)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof publicRegisterRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/forgot-password': {
      id: '/(public)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof publicForgotPasswordRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(private)/billing': {
      id: '/(private)/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof privateBillingRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/(dashboard)': {
      id: '/(private)/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privatedashboardRouteRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/subscription/reactivate/': {
      id: '/subscription/reactivate/'
      path: '/subscription/reactivate'
      fullPath: '/subscription/reactivate/'
      preLoaderRoute: typeof SubscriptionReactivateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/tasks/': {
      id: '/(private)/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof privateTasksIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/pos/': {
      id: '/(private)/pos/'
      path: '/pos'
      fullPath: '/pos/'
      preLoaderRoute: typeof privatePosIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/orders/': {
      id: '/(private)/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof privateOrdersIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/register/business-setup': {
      id: '/(public)/register/business-setup'
      path: '/business-setup'
      fullPath: '/register/business-setup'
      preLoaderRoute: typeof publicRegisterBusinessSetupRouteImport
      parentRoute: typeof publicRegisterRoute
    }
    '/(private)/(dashboard)/notifications': {
      id: '/(private)/(dashboard)/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof privatedashboardNotificationsRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/dashboard': {
      id: '/(private)/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof privatedashboardDashboardRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/contact-us': {
      id: '/(private)/(dashboard)/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof privatedashboardContactUsRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/settings': {
      id: '/(private)/(dashboard)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof privatedashboardSettingsRouteRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/business': {
      id: '/(private)/(dashboard)/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof privatedashboardBusinessRouteRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/billing': {
      id: '/(private)/(dashboard)/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof privatedashboardBillingRouteRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/account': {
      id: '/(private)/(dashboard)/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof privatedashboardAccountRouteRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/(supervisor)': {
      id: '/(private)/(dashboard)/(supervisor)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privatedashboardsupervisorRouteRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/(private)/(dashboard)/(admin)': {
      id: '/(private)/(dashboard)/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privatedashboardadminRouteRouteImport
      parentRoute: typeof privatedashboardRouteRoute
    }
    '/api/cron/daily/': {
      id: '/api/cron/daily/'
      path: '/api/cron/daily'
      fullPath: '/api/cron/daily/'
      preLoaderRoute: typeof ApiCronDailyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/webhook/': {
      id: '/api/billing/webhook/'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook/'
      preLoaderRoute: typeof ApiBillingWebhookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/tasks/create/': {
      id: '/(private)/tasks/create/'
      path: '/tasks/create'
      fullPath: '/tasks/create/'
      preLoaderRoute: typeof privateTasksCreateIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/tasks/$taskId/': {
      id: '/(private)/tasks/$taskId/'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId/'
      preLoaderRoute: typeof privateTasksTaskIdIndexRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/(dashboard)/settings/': {
      id: '/(private)/(dashboard)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof privatedashboardSettingsIndexRouteImport
      parentRoute: typeof privatedashboardSettingsRouteRoute
    }
    '/(private)/(dashboard)/business/': {
      id: '/(private)/(dashboard)/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof privatedashboardBusinessIndexRouteImport
      parentRoute: typeof privatedashboardBusinessRouteRoute
    }
    '/(private)/(dashboard)/billing/': {
      id: '/(private)/(dashboard)/billing/'
      path: '/'
      fullPath: '/billing/'
      preLoaderRoute: typeof privatedashboardBillingIndexRouteImport
      parentRoute: typeof privatedashboardBillingRouteRoute
    }
    '/(private)/(dashboard)/account/': {
      id: '/(private)/(dashboard)/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof privatedashboardAccountIndexRouteImport
      parentRoute: typeof privatedashboardAccountRouteRoute
    }
    '/api/billing/webhook/stripe': {
      id: '/api/billing/webhook/stripe'
      path: '/api/billing/webhook/stripe'
      fullPath: '/api/billing/webhook/stripe'
      preLoaderRoute: typeof ApiBillingWebhookStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/(dashboard)/settings/compliance': {
      id: '/(private)/(dashboard)/settings/compliance'
      path: '/compliance'
      fullPath: '/settings/compliance'
      preLoaderRoute: typeof privatedashboardSettingsComplianceRouteImport
      parentRoute: typeof privatedashboardSettingsRouteRoute
    }
    '/(private)/(dashboard)/billing/payment-methods': {
      id: '/(private)/(dashboard)/billing/payment-methods'
      path: '/payment-methods'
      fullPath: '/billing/payment-methods'
      preLoaderRoute: typeof privatedashboardBillingPaymentMethodsRouteImport
      parentRoute: typeof privatedashboardBillingRouteRoute
    }
    '/(private)/(dashboard)/billing/manual-payment': {
      id: '/(private)/(dashboard)/billing/manual-payment'
      path: '/manual-payment'
      fullPath: '/billing/manual-payment'
      preLoaderRoute: typeof privatedashboardBillingManualPaymentRouteImport
      parentRoute: typeof privatedashboardBillingRouteRoute
    }
    '/(private)/(dashboard)/(admin)/payment-approvals': {
      id: '/(private)/(dashboard)/(admin)/payment-approvals'
      path: '/payment-approvals'
      fullPath: '/payment-approvals'
      preLoaderRoute: typeof privatedashboardadminPaymentApprovalsRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/business/suppliers': {
      id: '/(private)/(dashboard)/business/suppliers'
      path: '/suppliers'
      fullPath: '/business/suppliers'
      preLoaderRoute: typeof privatedashboardBusinessSuppliersRouteRouteImport
      parentRoute: typeof privatedashboardBusinessRouteRoute
    }
    '/(private)/(dashboard)/business/subscription': {
      id: '/(private)/(dashboard)/business/subscription'
      path: '/subscription'
      fullPath: '/business/subscription'
      preLoaderRoute: typeof privatedashboardBusinessSubscriptionRouteRouteImport
      parentRoute: typeof privatedashboardBusinessRouteRoute
    }
    '/(private)/(dashboard)/business/customers': {
      id: '/(private)/(dashboard)/business/customers'
      path: '/customers'
      fullPath: '/business/customers'
      preLoaderRoute: typeof privatedashboardBusinessCustomersRouteRouteImport
      parentRoute: typeof privatedashboardBusinessRouteRoute
    }
    '/(private)/(dashboard)/(admin)/preparation': {
      id: '/(private)/(dashboard)/(admin)/preparation'
      path: '/preparation'
      fullPath: '/preparation'
      preLoaderRoute: typeof privatedashboardadminPreparationRouteRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/business/suppliers/': {
      id: '/(private)/(dashboard)/business/suppliers/'
      path: '/'
      fullPath: '/business/suppliers/'
      preLoaderRoute: typeof privatedashboardBusinessSuppliersIndexRouteImport
      parentRoute: typeof privatedashboardBusinessSuppliersRouteRoute
    }
    '/(private)/(dashboard)/business/subscription/': {
      id: '/(private)/(dashboard)/business/subscription/'
      path: '/'
      fullPath: '/business/subscription/'
      preLoaderRoute: typeof privatedashboardBusinessSubscriptionIndexRouteImport
      parentRoute: typeof privatedashboardBusinessSubscriptionRouteRoute
    }
    '/(private)/(dashboard)/business/profile/': {
      id: '/(private)/(dashboard)/business/profile/'
      path: '/profile'
      fullPath: '/business/profile/'
      preLoaderRoute: typeof privatedashboardBusinessProfileIndexRouteImport
      parentRoute: typeof privatedashboardBusinessRouteRoute
    }
    '/(private)/(dashboard)/business/permissions/': {
      id: '/(private)/(dashboard)/business/permissions/'
      path: '/permissions'
      fullPath: '/business/permissions/'
      preLoaderRoute: typeof privatedashboardBusinessPermissionsIndexRouteImport
      parentRoute: typeof privatedashboardBusinessRouteRoute
    }
    '/(private)/(dashboard)/business/customers/': {
      id: '/(private)/(dashboard)/business/customers/'
      path: '/'
      fullPath: '/business/customers/'
      preLoaderRoute: typeof privatedashboardBusinessCustomersIndexRouteImport
      parentRoute: typeof privatedashboardBusinessCustomersRouteRoute
    }
    '/(private)/(dashboard)/business/capabilities/': {
      id: '/(private)/(dashboard)/business/capabilities/'
      path: '/capabilities'
      fullPath: '/business/capabilities/'
      preLoaderRoute: typeof privatedashboardBusinessCapabilitiesIndexRouteImport
      parentRoute: typeof privatedashboardBusinessRouteRoute
    }
    '/(private)/(dashboard)/business/branches/': {
      id: '/(private)/(dashboard)/business/branches/'
      path: '/branches'
      fullPath: '/business/branches/'
      preLoaderRoute: typeof privatedashboardBusinessBranchesIndexRouteImport
      parentRoute: typeof privatedashboardBusinessRouteRoute
    }
    '/(private)/(dashboard)/account/security/': {
      id: '/(private)/(dashboard)/account/security/'
      path: '/security'
      fullPath: '/account/security/'
      preLoaderRoute: typeof privatedashboardAccountSecurityIndexRouteImport
      parentRoute: typeof privatedashboardAccountRouteRoute
    }
    '/(private)/(dashboard)/account/preferences/': {
      id: '/(private)/(dashboard)/account/preferences/'
      path: '/preferences'
      fullPath: '/account/preferences/'
      preLoaderRoute: typeof privatedashboardAccountPreferencesIndexRouteImport
      parentRoute: typeof privatedashboardAccountRouteRoute
    }
    '/(private)/(dashboard)/(supervisor)/transactions/': {
      id: '/(private)/(dashboard)/(supervisor)/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof privatedashboardsupervisorTransactionsIndexRouteImport
      parentRoute: typeof privatedashboardsupervisorRouteRoute
    }
    '/(private)/(dashboard)/(supervisor)/sales-reports/': {
      id: '/(private)/(dashboard)/(supervisor)/sales-reports/'
      path: '/sales-reports'
      fullPath: '/sales-reports/'
      preLoaderRoute: typeof privatedashboardsupervisorSalesReportsIndexRouteImport
      parentRoute: typeof privatedashboardsupervisorRouteRoute
    }
    '/(private)/(dashboard)/(supervisor)/order-history/': {
      id: '/(private)/(dashboard)/(supervisor)/order-history/'
      path: '/order-history'
      fullPath: '/order-history/'
      preLoaderRoute: typeof privatedashboardsupervisorOrderHistoryIndexRouteImport
      parentRoute: typeof privatedashboardsupervisorRouteRoute
    }
    '/(private)/(dashboard)/(supervisor)/inventory-reports/': {
      id: '/(private)/(dashboard)/(supervisor)/inventory-reports/'
      path: '/inventory-reports'
      fullPath: '/inventory-reports/'
      preLoaderRoute: typeof privatedashboardsupervisorInventoryReportsIndexRouteImport
      parentRoute: typeof privatedashboardsupervisorRouteRoute
    }
    '/(private)/(dashboard)/(admin)/purchases/': {
      id: '/(private)/(dashboard)/(admin)/purchases/'
      path: '/purchases'
      fullPath: '/purchases/'
      preLoaderRoute: typeof privatedashboardadminPurchasesIndexRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/(admin)/products/': {
      id: '/(private)/(dashboard)/(admin)/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof privatedashboardadminProductsIndexRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/(admin)/preparation/': {
      id: '/(private)/(dashboard)/(admin)/preparation/'
      path: '/'
      fullPath: '/preparation/'
      preLoaderRoute: typeof privatedashboardadminPreparationIndexRouteImport
      parentRoute: typeof privatedashboardadminPreparationRouteRoute
    }
    '/(private)/(dashboard)/(admin)/ingredients/': {
      id: '/(private)/(dashboard)/(admin)/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof privatedashboardadminIngredientsIndexRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/(admin)/employees/': {
      id: '/(private)/(dashboard)/(admin)/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof privatedashboardadminEmployeesIndexRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/(admin)/preparation/history': {
      id: '/(private)/(dashboard)/(admin)/preparation/history'
      path: '/history'
      fullPath: '/preparation/history'
      preLoaderRoute: typeof privatedashboardadminPreparationHistoryRouteImport
      parentRoute: typeof privatedashboardadminPreparationRouteRoute
    }
    '/(private)/(dashboard)/business/subscription/success/': {
      id: '/(private)/(dashboard)/business/subscription/success/'
      path: '/success'
      fullPath: '/business/subscription/success/'
      preLoaderRoute: typeof privatedashboardBusinessSubscriptionSuccessIndexRouteImport
      parentRoute: typeof privatedashboardBusinessSubscriptionRouteRoute
    }
    '/(private)/(dashboard)/business/subscription/quotes/': {
      id: '/(private)/(dashboard)/business/subscription/quotes/'
      path: '/quotes'
      fullPath: '/business/subscription/quotes/'
      preLoaderRoute: typeof privatedashboardBusinessSubscriptionQuotesIndexRouteImport
      parentRoute: typeof privatedashboardBusinessSubscriptionRouteRoute
    }
    '/(private)/(dashboard)/business/subscription/pricing/': {
      id: '/(private)/(dashboard)/business/subscription/pricing/'
      path: '/pricing'
      fullPath: '/business/subscription/pricing/'
      preLoaderRoute: typeof privatedashboardBusinessSubscriptionPricingIndexRouteImport
      parentRoute: typeof privatedashboardBusinessSubscriptionRouteRoute
    }
    '/(private)/(dashboard)/business/subscription/plans/': {
      id: '/(private)/(dashboard)/business/subscription/plans/'
      path: '/plans'
      fullPath: '/business/subscription/plans/'
      preLoaderRoute: typeof privatedashboardBusinessSubscriptionPlansIndexRouteImport
      parentRoute: typeof privatedashboardBusinessSubscriptionRouteRoute
    }
    '/(private)/(dashboard)/business/subscription/invoices/': {
      id: '/(private)/(dashboard)/business/subscription/invoices/'
      path: '/invoices'
      fullPath: '/business/subscription/invoices/'
      preLoaderRoute: typeof privatedashboardBusinessSubscriptionInvoicesIndexRouteImport
      parentRoute: typeof privatedashboardBusinessSubscriptionRouteRoute
    }
    '/(private)/(dashboard)/business/subscription/credits/': {
      id: '/(private)/(dashboard)/business/subscription/credits/'
      path: '/credits'
      fullPath: '/business/subscription/credits/'
      preLoaderRoute: typeof privatedashboardBusinessSubscriptionCreditsIndexRouteImport
      parentRoute: typeof privatedashboardBusinessSubscriptionRouteRoute
    }
    '/(private)/(dashboard)/business/permissions/audit/': {
      id: '/(private)/(dashboard)/business/permissions/audit/'
      path: '/permissions/audit'
      fullPath: '/business/permissions/audit/'
      preLoaderRoute: typeof privatedashboardBusinessPermissionsAuditIndexRouteImport
      parentRoute: typeof privatedashboardBusinessRouteRoute
    }
    '/(private)/(dashboard)/(supervisor)/transactions/$transactionId/': {
      id: '/(private)/(dashboard)/(supervisor)/transactions/$transactionId/'
      path: '/transactions/$transactionId'
      fullPath: '/transactions/$transactionId/'
      preLoaderRoute: typeof privatedashboardsupervisorTransactionsTransactionIdIndexRouteImport
      parentRoute: typeof privatedashboardsupervisorRouteRoute
    }
    '/(private)/(dashboard)/(supervisor)/order-history/$orderId/': {
      id: '/(private)/(dashboard)/(supervisor)/order-history/$orderId/'
      path: '/order-history/$orderId'
      fullPath: '/order-history/$orderId/'
      preLoaderRoute: typeof privatedashboardsupervisorOrderHistoryOrderIdIndexRouteImport
      parentRoute: typeof privatedashboardsupervisorRouteRoute
    }
    '/(private)/(dashboard)/(admin)/purchases/$purchaseId/': {
      id: '/(private)/(dashboard)/(admin)/purchases/$purchaseId/'
      path: '/purchases/$purchaseId'
      fullPath: '/purchases/$purchaseId/'
      preLoaderRoute: typeof privatedashboardadminPurchasesPurchaseIdIndexRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/(admin)/products/create/': {
      id: '/(private)/(dashboard)/(admin)/products/create/'
      path: '/products/create'
      fullPath: '/products/create/'
      preLoaderRoute: typeof privatedashboardadminProductsCreateIndexRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/(admin)/products/$productId/': {
      id: '/(private)/(dashboard)/(admin)/products/$productId/'
      path: '/products/$productId'
      fullPath: '/products/$productId/'
      preLoaderRoute: typeof privatedashboardadminProductsProductIdIndexRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/(admin)/ingredients/create/': {
      id: '/(private)/(dashboard)/(admin)/ingredients/create/'
      path: '/ingredients/create'
      fullPath: '/ingredients/create/'
      preLoaderRoute: typeof privatedashboardadminIngredientsCreateIndexRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/(admin)/ingredients/$ingredientId/': {
      id: '/(private)/(dashboard)/(admin)/ingredients/$ingredientId/'
      path: '/ingredients/$ingredientId'
      fullPath: '/ingredients/$ingredientId/'
      preLoaderRoute: typeof privatedashboardadminIngredientsIngredientIdIndexRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/(admin)/employees/create/': {
      id: '/(private)/(dashboard)/(admin)/employees/create/'
      path: '/employees/create'
      fullPath: '/employees/create/'
      preLoaderRoute: typeof privatedashboardadminEmployeesCreateIndexRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/(admin)/employees/$employeeId/': {
      id: '/(private)/(dashboard)/(admin)/employees/$employeeId/'
      path: '/employees/$employeeId'
      fullPath: '/employees/$employeeId/'
      preLoaderRoute: typeof privatedashboardadminEmployeesEmployeeIdIndexRouteImport
      parentRoute: typeof privatedashboardadminRouteRoute
    }
    '/(private)/(dashboard)/business/subscription/quotes/$quoteId/': {
      id: '/(private)/(dashboard)/business/subscription/quotes/$quoteId/'
      path: '/quotes/$quoteId'
      fullPath: '/business/subscription/quotes/$quoteId/'
      preLoaderRoute: typeof privatedashboardBusinessSubscriptionQuotesQuoteIdIndexRouteImport
      parentRoute: typeof privatedashboardBusinessSubscriptionRouteRoute
    }
  }
}

interface privatedashboardadminPreparationRouteRouteChildren {
  privatedashboardadminPreparationHistoryRoute: typeof privatedashboardadminPreparationHistoryRoute
  privatedashboardadminPreparationIndexRoute: typeof privatedashboardadminPreparationIndexRoute
}

const privatedashboardadminPreparationRouteRouteChildren: privatedashboardadminPreparationRouteRouteChildren =
  {
    privatedashboardadminPreparationHistoryRoute:
      privatedashboardadminPreparationHistoryRoute,
    privatedashboardadminPreparationIndexRoute:
      privatedashboardadminPreparationIndexRoute,
  }

const privatedashboardadminPreparationRouteRouteWithChildren =
  privatedashboardadminPreparationRouteRoute._addFileChildren(
    privatedashboardadminPreparationRouteRouteChildren,
  )

interface privatedashboardadminRouteRouteChildren {
  privatedashboardadminPreparationRouteRoute: typeof privatedashboardadminPreparationRouteRouteWithChildren
  privatedashboardadminPaymentApprovalsRoute: typeof privatedashboardadminPaymentApprovalsRoute
  privatedashboardadminEmployeesIndexRoute: typeof privatedashboardadminEmployeesIndexRoute
  privatedashboardadminIngredientsIndexRoute: typeof privatedashboardadminIngredientsIndexRoute
  privatedashboardadminProductsIndexRoute: typeof privatedashboardadminProductsIndexRoute
  privatedashboardadminPurchasesIndexRoute: typeof privatedashboardadminPurchasesIndexRoute
  privatedashboardadminEmployeesEmployeeIdIndexRoute: typeof privatedashboardadminEmployeesEmployeeIdIndexRoute
  privatedashboardadminEmployeesCreateIndexRoute: typeof privatedashboardadminEmployeesCreateIndexRoute
  privatedashboardadminIngredientsIngredientIdIndexRoute: typeof privatedashboardadminIngredientsIngredientIdIndexRoute
  privatedashboardadminIngredientsCreateIndexRoute: typeof privatedashboardadminIngredientsCreateIndexRoute
  privatedashboardadminProductsProductIdIndexRoute: typeof privatedashboardadminProductsProductIdIndexRoute
  privatedashboardadminProductsCreateIndexRoute: typeof privatedashboardadminProductsCreateIndexRoute
  privatedashboardadminPurchasesPurchaseIdIndexRoute: typeof privatedashboardadminPurchasesPurchaseIdIndexRoute
}

const privatedashboardadminRouteRouteChildren: privatedashboardadminRouteRouteChildren =
  {
    privatedashboardadminPreparationRouteRoute:
      privatedashboardadminPreparationRouteRouteWithChildren,
    privatedashboardadminPaymentApprovalsRoute:
      privatedashboardadminPaymentApprovalsRoute,
    privatedashboardadminEmployeesIndexRoute:
      privatedashboardadminEmployeesIndexRoute,
    privatedashboardadminIngredientsIndexRoute:
      privatedashboardadminIngredientsIndexRoute,
    privatedashboardadminProductsIndexRoute:
      privatedashboardadminProductsIndexRoute,
    privatedashboardadminPurchasesIndexRoute:
      privatedashboardadminPurchasesIndexRoute,
    privatedashboardadminEmployeesEmployeeIdIndexRoute:
      privatedashboardadminEmployeesEmployeeIdIndexRoute,
    privatedashboardadminEmployeesCreateIndexRoute:
      privatedashboardadminEmployeesCreateIndexRoute,
    privatedashboardadminIngredientsIngredientIdIndexRoute:
      privatedashboardadminIngredientsIngredientIdIndexRoute,
    privatedashboardadminIngredientsCreateIndexRoute:
      privatedashboardadminIngredientsCreateIndexRoute,
    privatedashboardadminProductsProductIdIndexRoute:
      privatedashboardadminProductsProductIdIndexRoute,
    privatedashboardadminProductsCreateIndexRoute:
      privatedashboardadminProductsCreateIndexRoute,
    privatedashboardadminPurchasesPurchaseIdIndexRoute:
      privatedashboardadminPurchasesPurchaseIdIndexRoute,
  }

const privatedashboardadminRouteRouteWithChildren =
  privatedashboardadminRouteRoute._addFileChildren(
    privatedashboardadminRouteRouteChildren,
  )

interface privatedashboardsupervisorRouteRouteChildren {
  privatedashboardsupervisorInventoryReportsIndexRoute: typeof privatedashboardsupervisorInventoryReportsIndexRoute
  privatedashboardsupervisorOrderHistoryIndexRoute: typeof privatedashboardsupervisorOrderHistoryIndexRoute
  privatedashboardsupervisorSalesReportsIndexRoute: typeof privatedashboardsupervisorSalesReportsIndexRoute
  privatedashboardsupervisorTransactionsIndexRoute: typeof privatedashboardsupervisorTransactionsIndexRoute
  privatedashboardsupervisorOrderHistoryOrderIdIndexRoute: typeof privatedashboardsupervisorOrderHistoryOrderIdIndexRoute
  privatedashboardsupervisorTransactionsTransactionIdIndexRoute: typeof privatedashboardsupervisorTransactionsTransactionIdIndexRoute
}

const privatedashboardsupervisorRouteRouteChildren: privatedashboardsupervisorRouteRouteChildren =
  {
    privatedashboardsupervisorInventoryReportsIndexRoute:
      privatedashboardsupervisorInventoryReportsIndexRoute,
    privatedashboardsupervisorOrderHistoryIndexRoute:
      privatedashboardsupervisorOrderHistoryIndexRoute,
    privatedashboardsupervisorSalesReportsIndexRoute:
      privatedashboardsupervisorSalesReportsIndexRoute,
    privatedashboardsupervisorTransactionsIndexRoute:
      privatedashboardsupervisorTransactionsIndexRoute,
    privatedashboardsupervisorOrderHistoryOrderIdIndexRoute:
      privatedashboardsupervisorOrderHistoryOrderIdIndexRoute,
    privatedashboardsupervisorTransactionsTransactionIdIndexRoute:
      privatedashboardsupervisorTransactionsTransactionIdIndexRoute,
  }

const privatedashboardsupervisorRouteRouteWithChildren =
  privatedashboardsupervisorRouteRoute._addFileChildren(
    privatedashboardsupervisorRouteRouteChildren,
  )

interface privatedashboardAccountRouteRouteChildren {
  privatedashboardAccountIndexRoute: typeof privatedashboardAccountIndexRoute
  privatedashboardAccountPreferencesIndexRoute: typeof privatedashboardAccountPreferencesIndexRoute
  privatedashboardAccountSecurityIndexRoute: typeof privatedashboardAccountSecurityIndexRoute
}

const privatedashboardAccountRouteRouteChildren: privatedashboardAccountRouteRouteChildren =
  {
    privatedashboardAccountIndexRoute: privatedashboardAccountIndexRoute,
    privatedashboardAccountPreferencesIndexRoute:
      privatedashboardAccountPreferencesIndexRoute,
    privatedashboardAccountSecurityIndexRoute:
      privatedashboardAccountSecurityIndexRoute,
  }

const privatedashboardAccountRouteRouteWithChildren =
  privatedashboardAccountRouteRoute._addFileChildren(
    privatedashboardAccountRouteRouteChildren,
  )

interface privatedashboardBillingRouteRouteChildren {
  privatedashboardBillingManualPaymentRoute: typeof privatedashboardBillingManualPaymentRoute
  privatedashboardBillingPaymentMethodsRoute: typeof privatedashboardBillingPaymentMethodsRoute
  privatedashboardBillingIndexRoute: typeof privatedashboardBillingIndexRoute
}

const privatedashboardBillingRouteRouteChildren: privatedashboardBillingRouteRouteChildren =
  {
    privatedashboardBillingManualPaymentRoute:
      privatedashboardBillingManualPaymentRoute,
    privatedashboardBillingPaymentMethodsRoute:
      privatedashboardBillingPaymentMethodsRoute,
    privatedashboardBillingIndexRoute: privatedashboardBillingIndexRoute,
  }

const privatedashboardBillingRouteRouteWithChildren =
  privatedashboardBillingRouteRoute._addFileChildren(
    privatedashboardBillingRouteRouteChildren,
  )

interface privatedashboardBusinessCustomersRouteRouteChildren {
  privatedashboardBusinessCustomersIndexRoute: typeof privatedashboardBusinessCustomersIndexRoute
}

const privatedashboardBusinessCustomersRouteRouteChildren: privatedashboardBusinessCustomersRouteRouteChildren =
  {
    privatedashboardBusinessCustomersIndexRoute:
      privatedashboardBusinessCustomersIndexRoute,
  }

const privatedashboardBusinessCustomersRouteRouteWithChildren =
  privatedashboardBusinessCustomersRouteRoute._addFileChildren(
    privatedashboardBusinessCustomersRouteRouteChildren,
  )

interface privatedashboardBusinessSubscriptionRouteRouteChildren {
  privatedashboardBusinessSubscriptionIndexRoute: typeof privatedashboardBusinessSubscriptionIndexRoute
  privatedashboardBusinessSubscriptionCreditsIndexRoute: typeof privatedashboardBusinessSubscriptionCreditsIndexRoute
  privatedashboardBusinessSubscriptionInvoicesIndexRoute: typeof privatedashboardBusinessSubscriptionInvoicesIndexRoute
  privatedashboardBusinessSubscriptionPlansIndexRoute: typeof privatedashboardBusinessSubscriptionPlansIndexRoute
  privatedashboardBusinessSubscriptionPricingIndexRoute: typeof privatedashboardBusinessSubscriptionPricingIndexRoute
  privatedashboardBusinessSubscriptionQuotesIndexRoute: typeof privatedashboardBusinessSubscriptionQuotesIndexRoute
  privatedashboardBusinessSubscriptionSuccessIndexRoute: typeof privatedashboardBusinessSubscriptionSuccessIndexRoute
  privatedashboardBusinessSubscriptionQuotesQuoteIdIndexRoute: typeof privatedashboardBusinessSubscriptionQuotesQuoteIdIndexRoute
}

const privatedashboardBusinessSubscriptionRouteRouteChildren: privatedashboardBusinessSubscriptionRouteRouteChildren =
  {
    privatedashboardBusinessSubscriptionIndexRoute:
      privatedashboardBusinessSubscriptionIndexRoute,
    privatedashboardBusinessSubscriptionCreditsIndexRoute:
      privatedashboardBusinessSubscriptionCreditsIndexRoute,
    privatedashboardBusinessSubscriptionInvoicesIndexRoute:
      privatedashboardBusinessSubscriptionInvoicesIndexRoute,
    privatedashboardBusinessSubscriptionPlansIndexRoute:
      privatedashboardBusinessSubscriptionPlansIndexRoute,
    privatedashboardBusinessSubscriptionPricingIndexRoute:
      privatedashboardBusinessSubscriptionPricingIndexRoute,
    privatedashboardBusinessSubscriptionQuotesIndexRoute:
      privatedashboardBusinessSubscriptionQuotesIndexRoute,
    privatedashboardBusinessSubscriptionSuccessIndexRoute:
      privatedashboardBusinessSubscriptionSuccessIndexRoute,
    privatedashboardBusinessSubscriptionQuotesQuoteIdIndexRoute:
      privatedashboardBusinessSubscriptionQuotesQuoteIdIndexRoute,
  }

const privatedashboardBusinessSubscriptionRouteRouteWithChildren =
  privatedashboardBusinessSubscriptionRouteRoute._addFileChildren(
    privatedashboardBusinessSubscriptionRouteRouteChildren,
  )

interface privatedashboardBusinessSuppliersRouteRouteChildren {
  privatedashboardBusinessSuppliersIndexRoute: typeof privatedashboardBusinessSuppliersIndexRoute
}

const privatedashboardBusinessSuppliersRouteRouteChildren: privatedashboardBusinessSuppliersRouteRouteChildren =
  {
    privatedashboardBusinessSuppliersIndexRoute:
      privatedashboardBusinessSuppliersIndexRoute,
  }

const privatedashboardBusinessSuppliersRouteRouteWithChildren =
  privatedashboardBusinessSuppliersRouteRoute._addFileChildren(
    privatedashboardBusinessSuppliersRouteRouteChildren,
  )

interface privatedashboardBusinessRouteRouteChildren {
  privatedashboardBusinessCustomersRouteRoute: typeof privatedashboardBusinessCustomersRouteRouteWithChildren
  privatedashboardBusinessSubscriptionRouteRoute: typeof privatedashboardBusinessSubscriptionRouteRouteWithChildren
  privatedashboardBusinessSuppliersRouteRoute: typeof privatedashboardBusinessSuppliersRouteRouteWithChildren
  privatedashboardBusinessIndexRoute: typeof privatedashboardBusinessIndexRoute
  privatedashboardBusinessBranchesIndexRoute: typeof privatedashboardBusinessBranchesIndexRoute
  privatedashboardBusinessCapabilitiesIndexRoute: typeof privatedashboardBusinessCapabilitiesIndexRoute
  privatedashboardBusinessPermissionsIndexRoute: typeof privatedashboardBusinessPermissionsIndexRoute
  privatedashboardBusinessProfileIndexRoute: typeof privatedashboardBusinessProfileIndexRoute
  privatedashboardBusinessPermissionsAuditIndexRoute: typeof privatedashboardBusinessPermissionsAuditIndexRoute
}

const privatedashboardBusinessRouteRouteChildren: privatedashboardBusinessRouteRouteChildren =
  {
    privatedashboardBusinessCustomersRouteRoute:
      privatedashboardBusinessCustomersRouteRouteWithChildren,
    privatedashboardBusinessSubscriptionRouteRoute:
      privatedashboardBusinessSubscriptionRouteRouteWithChildren,
    privatedashboardBusinessSuppliersRouteRoute:
      privatedashboardBusinessSuppliersRouteRouteWithChildren,
    privatedashboardBusinessIndexRoute: privatedashboardBusinessIndexRoute,
    privatedashboardBusinessBranchesIndexRoute:
      privatedashboardBusinessBranchesIndexRoute,
    privatedashboardBusinessCapabilitiesIndexRoute:
      privatedashboardBusinessCapabilitiesIndexRoute,
    privatedashboardBusinessPermissionsIndexRoute:
      privatedashboardBusinessPermissionsIndexRoute,
    privatedashboardBusinessProfileIndexRoute:
      privatedashboardBusinessProfileIndexRoute,
    privatedashboardBusinessPermissionsAuditIndexRoute:
      privatedashboardBusinessPermissionsAuditIndexRoute,
  }

const privatedashboardBusinessRouteRouteWithChildren =
  privatedashboardBusinessRouteRoute._addFileChildren(
    privatedashboardBusinessRouteRouteChildren,
  )

interface privatedashboardSettingsRouteRouteChildren {
  privatedashboardSettingsComplianceRoute: typeof privatedashboardSettingsComplianceRoute
  privatedashboardSettingsIndexRoute: typeof privatedashboardSettingsIndexRoute
}

const privatedashboardSettingsRouteRouteChildren: privatedashboardSettingsRouteRouteChildren =
  {
    privatedashboardSettingsComplianceRoute:
      privatedashboardSettingsComplianceRoute,
    privatedashboardSettingsIndexRoute: privatedashboardSettingsIndexRoute,
  }

const privatedashboardSettingsRouteRouteWithChildren =
  privatedashboardSettingsRouteRoute._addFileChildren(
    privatedashboardSettingsRouteRouteChildren,
  )

interface privatedashboardRouteRouteChildren {
  privatedashboardadminRouteRoute: typeof privatedashboardadminRouteRouteWithChildren
  privatedashboardsupervisorRouteRoute: typeof privatedashboardsupervisorRouteRouteWithChildren
  privatedashboardAccountRouteRoute: typeof privatedashboardAccountRouteRouteWithChildren
  privatedashboardBillingRouteRoute: typeof privatedashboardBillingRouteRouteWithChildren
  privatedashboardBusinessRouteRoute: typeof privatedashboardBusinessRouteRouteWithChildren
  privatedashboardSettingsRouteRoute: typeof privatedashboardSettingsRouteRouteWithChildren
  privatedashboardContactUsRoute: typeof privatedashboardContactUsRoute
  privatedashboardDashboardRoute: typeof privatedashboardDashboardRoute
  privatedashboardNotificationsRoute: typeof privatedashboardNotificationsRoute
}

const privatedashboardRouteRouteChildren: privatedashboardRouteRouteChildren = {
  privatedashboardadminRouteRoute: privatedashboardadminRouteRouteWithChildren,
  privatedashboardsupervisorRouteRoute:
    privatedashboardsupervisorRouteRouteWithChildren,
  privatedashboardAccountRouteRoute:
    privatedashboardAccountRouteRouteWithChildren,
  privatedashboardBillingRouteRoute:
    privatedashboardBillingRouteRouteWithChildren,
  privatedashboardBusinessRouteRoute:
    privatedashboardBusinessRouteRouteWithChildren,
  privatedashboardSettingsRouteRoute:
    privatedashboardSettingsRouteRouteWithChildren,
  privatedashboardContactUsRoute: privatedashboardContactUsRoute,
  privatedashboardDashboardRoute: privatedashboardDashboardRoute,
  privatedashboardNotificationsRoute: privatedashboardNotificationsRoute,
}

const privatedashboardRouteRouteWithChildren =
  privatedashboardRouteRoute._addFileChildren(
    privatedashboardRouteRouteChildren,
  )

interface privateRouteRouteChildren {
  privatedashboardRouteRoute: typeof privatedashboardRouteRouteWithChildren
  privateBillingRoute: typeof privateBillingRoute
  privateOrdersIndexRoute: typeof privateOrdersIndexRoute
  privatePosIndexRoute: typeof privatePosIndexRoute
  privateTasksIndexRoute: typeof privateTasksIndexRoute
  privateTasksTaskIdIndexRoute: typeof privateTasksTaskIdIndexRoute
  privateTasksCreateIndexRoute: typeof privateTasksCreateIndexRoute
}

const privateRouteRouteChildren: privateRouteRouteChildren = {
  privatedashboardRouteRoute: privatedashboardRouteRouteWithChildren,
  privateBillingRoute: privateBillingRoute,
  privateOrdersIndexRoute: privateOrdersIndexRoute,
  privatePosIndexRoute: privatePosIndexRoute,
  privateTasksIndexRoute: privateTasksIndexRoute,
  privateTasksTaskIdIndexRoute: privateTasksTaskIdIndexRoute,
  privateTasksCreateIndexRoute: privateTasksCreateIndexRoute,
}

const privateRouteRouteWithChildren = privateRouteRoute._addFileChildren(
  privateRouteRouteChildren,
)

interface publicRegisterRouteChildren {
  publicRegisterBusinessSetupRoute: typeof publicRegisterBusinessSetupRoute
}

const publicRegisterRouteChildren: publicRegisterRouteChildren = {
  publicRegisterBusinessSetupRoute: publicRegisterBusinessSetupRoute,
}

const publicRegisterRouteWithChildren = publicRegisterRoute._addFileChildren(
  publicRegisterRouteChildren,
)

interface publicRouteRouteChildren {
  publicForgotPasswordRoute: typeof publicForgotPasswordRoute
  publicLoginRoute: typeof publicLoginRoute
  publicRegisterRoute: typeof publicRegisterRouteWithChildren
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicForgotPasswordRoute: publicForgotPasswordRoute,
  publicLoginRoute: publicLoginRoute,
  publicRegisterRoute: publicRegisterRouteWithChildren,
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  privateRouteRoute: privateRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  SubscriptionReactivateIndexRoute: SubscriptionReactivateIndexRoute,
  ApiBillingWebhookStripeRoute: ApiBillingWebhookStripeRoute,
  ApiBillingWebhookIndexRoute: ApiBillingWebhookIndexRoute,
  ApiCronDailyIndexRoute: ApiCronDailyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
